---------------------------------------------------------------
--  TS02_AM_DATASHEET : Datasheet 테이블
---------------------------------------------------------------
CREATE TABLE TS02_AM_DATASHEET
(
    OID                 VARCHAR2(11 BYTE)   NOT NULL,
    STD_DATASHEET_OID   VARCHAR2(11 BYTE)   NULL,
    DATASHEET_TYPE      VARCHAR2(8 BYTE)   NULL,
    TITLE               VARCHAR2(255 BYTE)   NULL,

    DESCR               VARCHAR2(4000 BYTE) NULL,
    INPUT_USER          VARCHAR2(11 BYTE)   NULL,
 	INPUT_DATE 			DATE DEFAULT SYSDATE NOT NULL,
    MOD_USER            VARCHAR2(11 BYTE)   NULL,
    MOD_DATE            DATE                NULL,

    DEL_USER            VARCHAR2(11 BYTE)   NULL,
    DEL_DATE            DATE                NULL,
    CONSTRAINT TS02_AM_DATASHEET PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_AM_DATASHEET IS '문서정보 테이블';

COMMENT ON COLUMN TS02_AM_DATASHEET.OID IS 'OID';
COMMENT ON COLUMN TS02_AM_DATASHEET.STD_DATASHEET_OID IS '기준 DATASHEET OID';
COMMENT ON COLUMN TS02_AM_DATASHEET.DATASHEET_TYPE IS 'DATASHEET 타입';
COMMENT ON COLUMN TS02_AM_DATASHEET.TITLE IS '제목';

COMMENT ON COLUMN TS02_AM_DATASHEET.DESCR IS '설명';
COMMENT ON COLUMN TS02_AM_DATASHEET.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_AM_DATASHEET.INPUT_DATE IS '등록일';
COMMENT ON COLUMN TS02_AM_DATASHEET.MOD_USER IS '수정자';
COMMENT ON COLUMN TS02_AM_DATASHEET.MOD_DATE IS '수정일';

COMMENT ON COLUMN TS02_AM_DATASHEET.DEL_USER IS '삭제자';
COMMENT ON COLUMN TS02_AM_DATASHEET.DEL_DATE IS '삭제일';



---------------------------------------------------------------
--  TS02_AM_DATASHEET_ITEM : Datasheet 항목 테이블
---------------------------------------------------------------
CREATE TABLE TS02_AM_DATASHEET_ITEM
(
    OID                 VARCHAR2(11 BYTE)   NOT NULL,
    DATASHEET_OID       VARCHAR2(11 BYTE)   NOT NULL,
    NAME                VARCHAR2(255 BYTE)  NULL,
    ITEM_VALUE          VARCHAR2(255 BYTE)  NULL,
    ITEM_UNIT           VARCHAR2(255 BYTE)  NULL,
    
    ITEM_TYPE           VARCHAR2(4 BYTE)    NULL,
    ITEM_GROUP_CODE     VARCHAR2(8 BYTE)    NULL,
    TYPICAL             VARCHAR2(255 BYTE)  NULL,
    TEST_METHOD         VARCHAR2(255 BYTE)  NULL,
    
    X_LOC               VARCHAR2(20 BYTE)   NULL,
    Y_LOC               VARCHAR2(20 BYTE)   NULL,
    CONSTRAINT TS02_AM_DATASHEET_ITEM PRIMARY KEY( OID, DATASHEET_OID )
);

COMMENT ON TABLE TS02_AM_DATASHEET_ITEM IS 'DATASHEET 항목 테이블';

COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.OID IS 'OID';
COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.DATASHEET_OID IS 'DATASHEET OID';
COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.NAME IS '이름';
COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.ITEM_VALUE IS '아이템 값';
COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.ITEM_UNIT IS '아이템 단위';

COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.ITEM_TYPE IS '아이템 타입(라디오, 체크박스 등)';
COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.ITEM_GROUP_CODE IS '아이템 그룹 코드';
COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.TYPICAL IS '물성 전형';
COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.TEST_METHOD IS '시험 방법';

COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.X_LOC IS 'X 좌표';
COMMENT ON COLUMN TS02_AM_DATASHEET_ITEM.Y_LOC IS 'Y 좌표';


---------------------------------------------------------------
--  TS02_AM_DATASHEET_TARGET_ITEM : Datasheet 타겟의 Datasheet 항목 테이블
---------------------------------------------------------------
CREATE TABLE TS02_AM_DATASHEET_TARGET_ITEM
(
    OID                 VARCHAR2(11 BYTE) NOT NULL,
    DATASHEET_OID       VARCHAR2(11 BYTE) NOT NULL,
    TARGET_OID          VARCHAR2(11 BYTE) NOT NULL,
    TARGET_OBJECT       VARCHAR2(8 BYTE),
    ITEM_VALUE          VARCHAR2(255 BYTE),

    ITEM_UNIT           VARCHAR2(255 BYTE),
    ITEM_TYPE           VARCHAR2(4 BYTE),
    ITEM_GROUP_CODE     VARCHAR2(8 BYTE),
    X_LOC               VARCHAR2(20 BYTE),
    Y_LOC               VARCHAR2(20 BYTE),

    CONSTRAINT TS02_AM_DATASHEET_TARGET_ITEM PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_AM_DATASHEET_TARGET_ITEM IS 'DATASHEET 항목 테이블';

COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.OID IS 'OID';
COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.DATASHEET_OID IS 'DATASHEET OID';
COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.TARGET_OID IS '타겟 OID';
COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.TARGET_OBJECT IS '타겟 타입';
COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.ITEM_VALUE IS '아이템 값';

COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.ITEM_UNIT IS '아이템 단위';
COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.ITEM_TYPE IS '아이템 타입';
COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.ITEM_GROUP_CODE IS '아이템 그룹코드';
COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.X_LOC IS 'X 좌표';
COMMENT ON COLUMN TS02_AM_DATASHEET_TARGET_ITEM.Y_LOC IS 'Y 좌표';