---------------------------------------------------------------
-- TS02_TB_ROLE : Role을 관리 타입으로 사이트에서 수정해서 사용하게
---------------------------------------------------------------
CREATE TABLE TS02_TB_ROLE (
  OID 				VARCHAR2(11) 		NOT NULL,
  ROLE_NAME 		VARCHAR2(255) 		NOT NULL,
  ROLE_TYPE         VARCHAR2(8)         NOT NULL,
  INPUT_USER 		VARCHAR2(11) 			NULL,
  INPUT_DATE 		DATE DEFAULT SYSDATE 	NULL,

  CUSTOM_FIELD1 	VARCHAR2(255) 		NULL,
  CUSTOM_FIELD2 	VARCHAR2(255) 		NULL,
  CUSTOM_FIELD3 	VARCHAR2(255) 		NULL,
  CUSTOM_FIELD4 	VARCHAR2(255) 		NULL,
  CUSTOM_FIELD5 	VARCHAR2(255) 		NULL,
  CONSTRAINT TS02_TB_ROLE PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_ROLE IS 'Role 관리';

COMMENT ON COLUMN TS02_TB_ROLE.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_ROLE.ROLE_NAME IS '롤 이름';
COMMENT ON COLUMN TS02_TB_ROLE.ROLE_TYPE IS '롤 타입';
COMMENT ON COLUMN TS02_TB_ROLE.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_ROLE.INPUT_DATE IS '등록일시';

COMMENT ON COLUMN TS02_TB_ROLE.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_TB_ROLE.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_TB_ROLE.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_TB_ROLE.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_TB_ROLE.CUSTOM_FIELD5 IS '커스텀 필드5';



---------------------------------------------------------------
-- TS02_TB_ROLE_RIGHT : 권한관리 - 메뉴키와 해당 액션의 BITSUM으로 처리
---------------------------------------------------------------
CREATE TABLE TS02_TB_ROLE_RIGHT (
  ROLE_OID 				VARCHAR2(11) 		NOT NULL,
  TARGET_OBJECT 		VARCHAR2(4) 		NOT NULL,
  TARGET_OID 			VARCHAR2(11) 		NOT NULL,
  ACL_VALUE 			NUMBER(5) 			NULL,
  CONSTRAINT TS02_TB_RIGHT PRIMARY KEY( ROLE_OID, TARGET_OBJECT, TARGET_OID )
);

COMMENT ON TABLE TS02_TB_ROLE_RIGHT IS '권한관리 - 메뉴키와 해당 액션들을 BITSUM으로 계산하여 처리';

COMMENT ON COLUMN TS02_TB_ROLE_RIGHT.ROLE_OID IS 'ROLE OID';
COMMENT ON COLUMN TS02_TB_ROLE_RIGHT.TARGET_OBJECT IS '타겟 객체';
COMMENT ON COLUMN TS02_TB_ROLE_RIGHT.TARGET_OID IS '타겟 키';
COMMENT ON COLUMN TS02_TB_ROLE_RIGHT.ACL_VALUE IS 'bitsum으로 처리 ACLObject 값을 가지고 있음';





---------------------------------------------------------------
-- TS02_TB_ROLE_USER_REL : Role에 포함된 사용자타겟 정보 - 타겟은 User, Group, Pgroup
---------------------------------------------------------------
CREATE TABLE TS02_TB_ROLE_USER_REL (
  ROLE_OID 				VARCHAR2(11) 		NOT NULL,
  TARGET_OBJECT 		VARCHAR2(4) 		NOT NULL,
  TARGET_OID 			VARCHAR2(11) 		NOT NULL,
  
  ROLE_START_DATE		DATE					NULL,
  ROLE_END_DATE			DATE					NULL,
  INPUT_USER 			VARCHAR2(11) 			NULL,
  INPUT_DATE			DATE DEFAULT SYSDATE 	NULL,
  
  CONSTRAINT TS02_TB_ROLE_USER_REL PRIMARY KEY( ROLE_OID, TARGET_OID )
);

COMMENT ON TABLE TS02_TB_ROLE_USER_REL IS 'Role에 포함된 사용자타겟 정보 - 타겟은 User, Group, Pgroup';

COMMENT ON COLUMN TS02_TB_ROLE_USER_REL.ROLE_OID IS 'ROLE OID';
COMMENT ON COLUMN TS02_TB_ROLE_USER_REL.TARGET_OBJECT IS '타겟 객체';
COMMENT ON COLUMN TS02_TB_ROLE_USER_REL.TARGET_OID IS '타겟 OID';

COMMENT ON COLUMN TS02_TB_ROLE_USER_REL.ROLE_START_DATE IS 'ROLE 시작일시';
COMMENT ON COLUMN TS02_TB_ROLE_USER_REL.ROLE_END_DATE IS 'ROLE 종료일시';
COMMENT ON COLUMN TS02_TB_ROLE_USER_REL.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_ROLE_USER_REL.INPUT_DATE IS '등록일';
