-- TS02_TB_AUDIT_FILE_DOWN : 파일 다운로드 이력
DROP TABLE TS02_TB_AUDIT_FILE_DOWN;

--  TS02_TB_AUDIT_VIEW : 조회 이력 테이블 - 게시물은 별도처리
DROP TABLE TS02_TB_AUDIT_VIEW;

--  TS02_TB_AUDIT_VISIT ㅣ 방문 이력 테이블
DROP TABLE TS02_TB_AUDIT_VISIT;

