---------------------------------------------------------------
--  TS02_AM_MATERIAL : 소재 구분 테이블
---------------------------------------------------------------
CREATE TABLE TS02_AM_MATERIAL 
(	
   	OID 		VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	SYSTEM_OID 	VARCHAR2(11 BYTE),
	
	CONSTRAINT TS02_AM_MATERIAL PRIMARY KEY( OID )
);

COMMENT ON COLUMN TS02_AM_MATERIAL.OID IS 'OID';
COMMENT ON COLUMN TS02_AM_MATERIAL.SYSTEM_OID IS '시스템 OID';

COMMENT ON TABLE TS02_AM_MATERIAL  IS '소재 구분 테이블';



---------------------------------------------------------------
--  TS02_AM_MATERIAL_LANG : 소재 구분 다국어 테이블
---------------------------------------------------------------
CREATE TABLE TS02_AM_MATERIAL_LANG
(
    OID                 VARCHAR2(11 BYTE)       NOT NULL,
    LANG                VARCHAR2(2 BYTE) 		NOT NULL,
    NAME                VARCHAR2(255 BYTE)      NULL,
    CLASS_NAME          VARCHAR2(255 BYTE)      NULL,
    DESCR				VARCHAR2(4000 BYTE)		NULL,
    INPUT_USER          VARCHAR2(11)        	NULL,
    INPUT_DATE          DATE DEFAULT SYSDATE	NULL,

    MOD_USER            VARCHAR2(11)        	NULL,
    MOD_DATE            DATE                	NULL,

    CONSTRAINT TS02_AM_MATERIAL_LANG PRIMARY KEY( OID, LANG )
);

COMMENT ON TABLE TS02_AM_MATERIAL_LANG IS '소재 구분 다국어 테이블';

COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.OID IS 'OID';
COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.LANG IS 'LANG 한글 ko, 영어 en, 중국어 cn';
COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.NAME IS '소재 구분명';
COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.CLASS_NAME IS '소재 구분 부제';
COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.DESCR IS '소재 구분 설명';


COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.INPUT_DATE IS '등록일시';

COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.MOD_USER IS '수정자';
COMMENT ON COLUMN TS02_AM_MATERIAL_LANG.MOD_DATE IS '수정일시';
