---------------------------------------------------------------
-- Role을 가진 사용자 뷰
-- 사용 테이블 : TS02_TB_USER, TS02_TB_ROLE_USER_REL, TS02_TB_ROLE
---------------------------------------------------------------
CREATE OR REPLACE VIEW VS02_USER_ROLE AS
SELECT
	U.OID OID,
	U.ID,
	U.NAME,
	U.EMAIL,
  
	U.STATUS_TYPE_FLAG,
  	U.USER_TYPE,
  	U.COMPANY_OID,

	U.GROUP_OID,
	U.BRANCH_OID,
	U.RANK,
	U.POSITION,
	
  	U.INPUT_DATE,
	U.CUSTOM_FIELD1,
	U.CUSTOM_FIELD2,
  
	U.TEL_PART1,
	U.TEL_PART2,
	U.TEL_PART3,
	U.PHONE_PART1,
	U.PHONE_PART2,
	U.PHONE_PART3,
	U.JOIN_PATH_DESCR,
	
	R.OID ROLE_OID,
	R.ROLE_NAME,
		
	REL.TARGET_OBJECT,
    REL.ROLE_START_DATE ROLE_START_DATE,
    REL.ROLE_END_DATE ROLE_END_DATE
FROM TS02_TB_USER U
JOIN TS02_TB_ROLE_USER_REL REL
ON U.OID = REL.TARGET_OID
AND REL.TARGET_OBJECT  = 'FWUR'
JOIN TS02_TB_ROLE R
ON REL.ROLE_OID = R.OID;

