---------------------------------------------------------------
-- TS02_TB_MSG_BOOKING : 메시지 예약 테이블
-- 메시지 설정을 따로 하지 않고 메시지에서 바로 예약을 할수도 있도록
-- 주기적으로 체크해서 예약처리  - 예약 주기는 10분단위로 처리
---------------------------------------------------------------
CREATE TABLE TS02_TB_MSG_BOOKING
(
	OID             				VARCHAR2(11)      	NOT NULL,
	MSG_OID 						VARCHAR2(11)    	NULL,
	PART_OID                        VARCHAR2(11)        NULL,
    BOOKING_DAY 					DATE   		 		NULL,
	BOOKING_TIME 					DATE   		 		NULL,

    PROCESS_TYPE_FLAG 				CHAR(1) 	  		NULL,
	INPUT_USER      				VARCHAR2(11)      	NOT NULL,
 	INPUT_DATE 						DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT TS02_TB_MSG_BOOKING PRIMARY KEY (OID)
);

COMMENT ON TABLE TS02_TB_MSG_BOOKING IS '메시지 예약 테이블';

COMMENT ON COLUMN TS02_TB_MSG_BOOKING.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_MSG_BOOKING.MSG_OID IS '메세지 OID';
COMMENT ON COLUMN TS02_TB_MSG_BOOKING.PART_OID IS 'PART OID';
COMMENT ON COLUMN TS02_TB_MSG_BOOKING.BOOKING_DAY IS '예약일자 - 년:월:일을 저장';
COMMENT ON COLUMN TS02_TB_MSG_BOOKING.BOOKING_TIME IS '예약시간 - 시간:분:초를 저장';

COMMENT ON COLUMN TS02_TB_MSG_BOOKING.PROCESS_TYPE_FLAG IS '프로세스 대기 W, 완료 D';
COMMENT ON COLUMN TS02_TB_MSG_BOOKING.INPUT_USER IS '생성자';
COMMENT ON COLUMN TS02_TB_MSG_BOOKING.INPUT_DATE IS '생성일자';



---------------------------------------------------------------
-- TS02_TB_MSG_GROUP  : 메시지 그룹 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_MSG_GROUP
(
    OID         		VARCHAR2(11)       		NOT NULL,
    BRANCH_OID			VARCHAR2(11)			NULL,
    PART_OID            VARCHAR2(11)            NULL,
    NAME        		VARCHAR2(255)   		NOT NULL,
	DESCR 				VARCHAR2(500)   		NULL,

	ORDER_NO 			NUMBER(5)	   			NULL,
	INPUT_USER  		VARCHAR2(11)       		NOT NULL,
    INPUT_DATE  		DATE       				NOT NULL,
    CONSTRAINT TS02_TB_MSG_GROUP PRIMARY KEY (OID)
);

COMMENT ON TABLE TS02_TB_MSG_GROUP IS '메시지 그룹 테이블';

COMMENT ON COLUMN TS02_TB_MSG_GROUP.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_MSG_GROUP.BRANCH_OID IS '지점 OID';
COMMENT ON COLUMN TS02_TB_MSG_GROUP.PART_OID IS 'PART OID';
COMMENT ON COLUMN TS02_TB_MSG_GROUP.NAME IS '그룹명';
COMMENT ON COLUMN TS02_TB_MSG_GROUP.DESCR IS '설명';

COMMENT ON COLUMN TS02_TB_MSG_GROUP.ORDER_NO IS '그룹 정렬순서';
COMMENT ON COLUMN TS02_TB_MSG_GROUP.INPUT_USER IS '생성자OID';
COMMENT ON COLUMN TS02_TB_MSG_GROUP.INPUT_DATE IS '생성일';




---------------------------------------------------------------
-- TS02_TB_MSG_GROUP_USER_REL : 메시지 그룹 관계테이블 - 메시지그룹에 속한 사용자 관리
---------------------------------------------------------------
CREATE TABLE TS02_TB_MSG_GROUP_USER_REL
(
    MSG_GROUP_OID   VARCHAR2(11)       	NOT NULL,
    USER_OID  		VARCHAR2(11)       	NOT NULL,
    INPUT_DATE  	DATE       			NOT NULL,

    CONSTRAINT TS02_TB_MSG_GROUP_USER_REL PRIMARY KEY (MSG_GROUP_OID, USER_OID)
);

COMMENT ON TABLE TS02_TB_MSG_GROUP_USER_REL IS '메시지그룹과 사용자 관계테이블';

COMMENT ON COLUMN TS02_TB_MSG_GROUP_USER_REL.MSG_GROUP_OID IS '메세지 그룹OID';
COMMENT ON COLUMN TS02_TB_MSG_GROUP_USER_REL.USER_OID IS '대상자 OID';
COMMENT ON COLUMN TS02_TB_MSG_GROUP_USER_REL.INPUT_DATE IS '생성일';






---------------------------------------------------------------
-- TS02_TB_MSG: 메시지 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_MSG
(
    OID            					VARCHAR2(11)        	NOT NULL,
    SYSTEM_OID                      VARCHAR2(11)			NULL,
    PART_OID						VARCHAR2(11)			NULL,
    MSG_TYPE_MODE					NUMBER(10)     			NULL,
    CLASS_TYPE						VARCHAR2(8) 			NULL,
    	
    NAME      	 					VARCHAR2(255)    		NULL,
    MSG_TEMPLATE_OID				VARCHAR2(11)			NULL,
    MSG_BOOKING_OID					VARCHAR2(11)			NULL,
    SEND_TYPE_FLAG					CHAR(1) 	  			NULL,
    REPLACE_MSG_YN					CHAR(1)					NULL,
    
    CONTENTS   	 					VARCHAR2(4000)   		NULL,
    IMAGE_URL1						VARCHAR2(255)  			NULL,
    IMAGE_URL2						VARCHAR2(255)  			NULL,
    IMAGE_URL3						VARCHAR2(255)  			NULL,

    LINK_URL1						VARCHAR2(500) 			NULL,
    LINK_URL2						VARCHAR2(500) 			NULL,
    LINK_URL3						VARCHAR2(500) 			NULL,
    INPUT_USER     					VARCHAR2(11)     		NOT NULL,
    INPUT_DATE     					DATE        			NOT NULL,

    CUSTOM_FIELD1  					VARCHAR2(255)   		NULL,
    CUSTOM_FIELD2  					VARCHAR2(255)    		NULL,
    CUSTOM_FIELD3  					VARCHAR2(255)    		NULL,
    CONSTRAINT TS02_TB_MSG PRIMARY KEY (OID)
);

COMMENT ON TABLE TS02_TB_MSG IS '메시지 테이블';

COMMENT ON COLUMN TS02_TB_MSG.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_MSG.SYSTEM_OID IS '시스템 OID';
COMMENT ON COLUMN TS02_TB_MSG.PART_OID IS 'PART OID';
COMMENT ON COLUMN TS02_TB_MSG.MSG_TYPE_MODE IS '메시지타입(친구톡/알림톡/SMS/Push/....)';
COMMENT ON COLUMN TS02_TB_MSG.CLASS_TYPE IS '분류코드 코드값을 지정해서 사용 ex) 활동보고, 공지사항';

COMMENT ON COLUMN TS02_TB_MSG.NAME IS '메세지명';
COMMENT ON COLUMN TS02_TB_MSG.MSG_TEMPLATE_OID IS '메세지 템플릿 OID';
COMMENT ON COLUMN TS02_TB_MSG.MSG_BOOKING_OID IS '메세지 예약 OID';
COMMENT ON COLUMN TS02_TB_MSG.SEND_TYPE_FLAG IS '발송방법 즉시발송 I, 예약발송 B';
COMMENT ON COLUMN TS02_TB_MSG.REPLACE_MSG_YN IS '대체문자 발송';

COMMENT ON COLUMN TS02_TB_MSG.CONTENTS IS '메세지 내용';
COMMENT ON COLUMN TS02_TB_MSG.IMAGE_URL1 IS '이미지 URL1';
COMMENT ON COLUMN TS02_TB_MSG.IMAGE_URL2 IS '이미지 URL2';
COMMENT ON COLUMN TS02_TB_MSG.IMAGE_URL3 IS '이미지 URL3';

COMMENT ON COLUMN TS02_TB_MSG.LINK_URL1 IS '링크 URL1';
COMMENT ON COLUMN TS02_TB_MSG.LINK_URL2 IS '링크 URL2';
COMMENT ON COLUMN TS02_TB_MSG.LINK_URL3 IS '링크 URL3';
COMMENT ON COLUMN TS02_TB_MSG.INPUT_USER IS '생성자';
COMMENT ON COLUMN TS02_TB_MSG.INPUT_DATE IS '생성일';

COMMENT ON COLUMN TS02_TB_MSG.CUSTOM_FIELD1 IS '커스텀 필드 1';
COMMENT ON COLUMN TS02_TB_MSG.CUSTOM_FIELD2 IS '커스텀 필드 2';
COMMENT ON COLUMN TS02_TB_MSG.CUSTOM_FIELD3 IS '커스텀 필드 3';







---------------------------------------------------------------
-- TS02_TB_MSG_SEND_RESULT : 메시지 발송 결과 테이블  추가
---------------------------------------------------------------
CREATE TABLE TS02_TB_MSG_SEND_RESULT
(
    OID            				VARCHAR2(11)        	NOT NULL,
    MSG_OID 					VARCHAR2(11)    		NULL,
    PART_OID					VARCHAR2(11)			NULL,

    SEND_TOTAL_CNT				NUMBER(10)				NULL,
    SEND_SUCCESS_CNT			NUMBER(10)				NULL,
    SEND_FAIL_CNT				NUMBER(10)				NULL,
    SEND_OPEN_CNT				NUMBER(10)				NULL,

    INPUT_USER     				VARCHAR2(11)     		NOT NULL,
    INPUT_DATE     				DATE        			NOT NULL,
    CUSTOM_FIELD1  				VARCHAR2(255)   		NULL,
    CUSTOM_FIELD2  				VARCHAR2(255)    		NULL,
    CUSTOM_FIELD3  				VARCHAR2(255)    		NULL,
    CONSTRAINT TS02_TB_MSG_SEND_RESULT PRIMARY KEY (OID)
);

COMMENT ON TABLE TS02_TB_MSG_SEND_RESULT IS '메시지 발송 결과 테이블';

COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.MSG_OID IS '메세지 OID';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.PART_OID IS 'PART OID';

COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.SEND_TOTAL_CNT IS '발송 총카운트';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.SEND_SUCCESS_CNT IS '발송 성공 카운트';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.SEND_FAIL_CNT IS '발송 실패 카운트';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.SEND_OPEN_CNT IS '발송 확인 카운트';

COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.INPUT_USER IS '발신인';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.INPUT_DATE IS '발송일시';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.CUSTOM_FIELD1 IS '커스텀 필드 1';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.CUSTOM_FIELD2 IS '커스텀 필드 2';
COMMENT ON COLUMN TS02_TB_MSG_SEND_RESULT.CUSTOM_FIELD3 IS '커스텀 필드 3';





---------------------------------------------------------------
-- TS02_TB_MSG_SEND_HIST : 메시지 발신 이력테이블 
---------------------------------------------------------------
CREATE TABLE TS02_TB_MSG_SEND_HIST
(
    OID           				VARCHAR2(11)    	NOT NULL,
    MSG_OID 					VARCHAR2(11)    	NULL,
    PART_OID					VARCHAR2(11)		NULL,
    MSG_TYPE       				VARCHAR2(8)  		NULL,
    RECEIVER_OID    			VARCHAR2(11)    	NULL,
    
    RECEIVER_PHONE				VARCHAR2(15)		NULL,
    RECEIVER_UUID 				VARCHAR2(36) 		NULL,
    SUCCESS_YN    				CHAR(1)     		NULL,
    ERROR_MSG 					VARCHAR2(255) 		NULL,
    REPLACE_OID					VARCHAR2(11)		NULL,
    
    OPEN_YN 	 				CHAR(1)     		NULL,
    OPEN_DATE     				DATE    			NULL,
    INPUT_DATE     				DATE    			NOT NULL,
    CONSTRAINT TS02_TB_MSG_SEND_HIST PRIMARY KEY (OID)
);

COMMENT ON TABLE TS02_TB_MSG_SEND_HIST IS '메시지 발신 이력테이블';

COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.MSG_OID IS '메세지 OID';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.PART_OID IS 'PART OID';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.MSG_TYPE IS '메시지타입(친구톡/알림톡/SMS/Push/....)';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.RECEIVER_OID IS '수신자 OID';

COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.RECEIVER_PHONE IS '수신자 번호';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.RECEIVER_UUID IS '설치된 DEVICE 고유 ID - Push용';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.SUCCESS_YN IS '발송 성공여부';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.ERROR_MSG IS '에러  메세지';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.REPLACE_OID IS '대체문자의 실패 이력 OID';

COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.OPEN_YN IS '확인여부';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.OPEN_DATE IS '확인일시';
COMMENT ON COLUMN TS02_TB_MSG_SEND_HIST.INPUT_DATE IS '생성일자';





---------------------------------------------------------------
-- TS02_TB_MSG_TEMPLATE : 메시지 템플릿 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_MSG_TEMPLATE
(
    OID             	VARCHAR2(11)      	NOT NULL,
	TARGET_OID          VARCHAR2(11)      	NULL,
	TARGET_OBJECT       VARCHAR2(4)      	NULL,
    
    PART_OID			VARCHAR2(11)		NULL,
    NAME            	VARCHAR2(255)  		NULL,
    CLASS_TYPE			VARCHAR2(8) 		NULL,
    CONTENTS			VARCHAR2(4000)  	NULL,

    TEMPLATE_ID			VARCHAR2(40)		NULL,
    IMAGE_URL1			VARCHAR2(500)  		NULL,
    IMAGE_URL2			VARCHAR2(500)  		NULL,
    IMAGE_URL3			VARCHAR2(500)  		NULL,

    LINK_URL1			VARCHAR2(500) 		NULL,
    LINK_URL2			VARCHAR2(500) 		NULL,
    LINK_URL3			VARCHAR2(500) 		NULL,
    INPUT_USER      	VARCHAR2(11)      	NOT NULL,
    INPUT_DATE      	DATE      			NOT NULL,
    CONSTRAINT TS02_TB_MSG_TEMPLATE PRIMARY KEY (OID)
);

COMMENT ON TABLE TS02_TB_MSG_TEMPLATE IS '메시지 템플릿 테이블';

COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.TARGET_OID IS '타겟 OID';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.TARGET_OBJECT IS '타겟 객체';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.PART_OID IS 'PART OID';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.NAME IS '템플릿명';

COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.CLASS_TYPE IS '분류코드 ex) 개인정보이용, 회원가입';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.CONTENTS IS '콘텐츠';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.TEMPLATE_ID IS '외부 API용 - 메시지 유형 템플릿 코드(알림톡 필수)';

COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.IMAGE_URL1 IS '이미지 URL1';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.IMAGE_URL2 IS '이미지 URL2';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.IMAGE_URL3 IS '이미지 URL3';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.LINK_URL1 IS '링크 URL1';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.LINK_URL2 IS '링크 URL2';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.LINK_URL3 IS '링크 URL3';

COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.INPUT_USER IS '생성자';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE.INPUT_DATE IS '생성일자';






---------------------------------------------------------------
-- TS02_TB_MSG_TEMPLATE_ITEM : 메시지 템플릿 아이템 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_MSG_TEMPLATE_ITEM
(
	OID					VARCHAR2(11)			NULL,
	MSG_TEMPLATE_OID  	VARCHAR2(11)      		NULL,
    ITEM_KEYS           VARCHAR2(2000)  		NULL,
    ITEM_VALUES         VARCHAR2(2000)  		NULL,

    CONSTRAINT TS02_TB_MSG_TEMPLATE_ITEM PRIMARY KEY (OID)
);

COMMENT ON TABLE TS02_TB_MSG_TEMPLATE_ITEM IS '메시지 템플릿 아이템 테이블';

COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE_ITEM.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE_ITEM.MSG_TEMPLATE_OID IS '메세지 템플릿 OID';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE_ITEM.ITEM_KEYS IS '아이템 키 		ex) 고객님	|주문상품명	|금액';
COMMENT ON COLUMN TS02_TB_MSG_TEMPLATE_ITEM.ITEM_VALUES IS '아이템 값 	ex) 홍길동	|테이블A		|230,000';
