---------------------------------------------------------------
-- TS02_TB_POSTING_AUDIT_VIEW  : 게시물 보기이력 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_POSTING_AUDIT_VIEW (
  OID 					VARCHAR2(11) 			NOT NULL,
  POSTING_OID 			VARCHAR2(11) 			NOT NULL,
  BOARD_OID 			VARCHAR2(11) 			NULL,
  
  VIEW_YEAR				VARCHAR(4)				NULL,
  VIEW_MONTH			VARCHAR(2) 				NULL,
  VIEW_WEEK				VARCHAR(1) 				NULL,
  VIEW_DAY				VARCHAR(2)				NULL,
  VIEW_HOUR				VARCHAR(2)	 			NULL,	
  
  VIEW_USER 			VARCHAR2(11) 			NULL,
  VIEW_DATE 			DATE DEFAULT SYSDATE 	NULL,
  VIEW_USER_IP    		VARCHAR2(20) 			NULL,

  CONSTRAINT TS02_TB_POSTING_AUDIT_VIEW PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_POSTING_AUDIT_VIEW IS '포스팅 보기이력 테이블';

COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.POSTING_OID IS 'POSTING OID';
COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.BOARD_OID IS 'BOARD OID';

COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.VIEW_YEAR IS '등록 년';
COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.VIEW_MONTH IS '등록 월';
COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.VIEW_WEEK IS '등록 주';
COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.VIEW_DAY IS '등록 일';
COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.VIEW_HOUR IS '등록 시간';


COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.VIEW_USER IS '본사람 OID';
COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.VIEW_DATE IS '본 일시';

COMMENT ON COLUMN TS02_TB_POSTING_AUDIT_VIEW.VIEW_USER_IP IS '본 사용자 IP';


---------------------------------------------------------------
-- TS02_TB_BOARD : 보드 테이블
-- Posting의 부모
-- POSTING_CNT, POSTING_CONTENTS_SIZE, POSTING_FILE_CNT, POSTING_FILE_SIZE은
-- 통계에서 넣어주도록 처리.
---------------------------------------------------------------
CREATE TABLE TS02_TB_BOARD (
  OID 							VARCHAR2(11) 			NOT NULL,
  TARGET_OBJECT 				VARCHAR2(4) 			NULL,
  TARGET_OID 					VARCHAR2(11) 			NULL,
  BOARD_TYPE_FLAG				CHAR(1) 				NULL,

  STATUS_TYPE_FLAG 				CHAR(1) DEFAULT 'U' 	NULL,
  NAME 							VARCHAR2(255) 			NULL,
  DESCR 						VARCHAR2(500) 			NULL,
  OWNER_USER 					VARCHAR2(11) 			NULL,
  OWNER_DATE 					DATE 					NULL,

  INPUT_USER 					VARCHAR2(11) 			NULL,
  INPUT_DATE 					DATE DEFAULT SYSDATE	NULL,
  MOD_USER 						VARCHAR2(11) 			NULL,
  MOD_DATE 						DATE 					NULL,
  DEL_USER 						VARCHAR2(11) 			NULL,
  DEL_DATE 						DATE 					NULL,
    
  CUSTOM_FIELD1 				VARCHAR2(255) 			NULL,
  CUSTOM_FIELD2 				VARCHAR2(255) 			NULL,
  CUSTOM_FIELD3 				VARCHAR2(255) 			NULL,
  CUSTOM_FIELD4 				VARCHAR2(255) 			NULL,
  CUSTOM_FIELD5 				VARCHAR2(255) 			NULL,
  
  CONSTRAINT TS02_TB_BOARD PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_BOARD IS '보드 테이블';

COMMENT ON COLUMN TS02_TB_BOARD.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_BOARD.TARGET_OBJECT IS '타겟 객체';
COMMENT ON COLUMN TS02_TB_BOARD.TARGET_OID IS '타겟 OID';
COMMENT ON COLUMN TS02_TB_BOARD.BOARD_TYPE_FLAG IS '보드 형태(일반, Q/A, 동영상 등등)';

COMMENT ON COLUMN TS02_TB_BOARD.STATUS_TYPE_FLAG IS '사용중 U, 중지 S, 폐쇄 X';
COMMENT ON COLUMN TS02_TB_BOARD.NAME IS '보드명';
COMMENT ON COLUMN TS02_TB_BOARD.DESCR IS '설명';
COMMENT ON COLUMN TS02_TB_BOARD.OWNER_USER IS '소유자, 담당자';
COMMENT ON COLUMN TS02_TB_BOARD.OWNER_DATE IS '소유일시';

COMMENT ON COLUMN TS02_TB_BOARD.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_BOARD.INPUT_DATE IS '등록일시';
COMMENT ON COLUMN TS02_TB_BOARD.MOD_USER IS '수정자';
COMMENT ON COLUMN TS02_TB_BOARD.MOD_DATE IS '수정일시';
COMMENT ON COLUMN TS02_TB_BOARD.DEL_USER IS '삭제자';
COMMENT ON COLUMN TS02_TB_BOARD.DEL_DATE IS '삭제일시';

COMMENT ON COLUMN TS02_TB_BOARD.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_TB_BOARD.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_TB_BOARD.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_TB_BOARD.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_TB_BOARD.CUSTOM_FIELD5 IS '커스텀 필드5';



---------------------------------------------------------------
-- TS02_TB_CONTENTS  : 컨텐츠 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_CONTENTS (
  OID 					VARCHAR2(11) 		NOT NULL,
  TARGET_OBJECT 		VARCHAR2(4) 		NULL,
  TARGET_OID			VARCHAR2(11) 		NULL,
  CONTENTS 				CLOB 				NULL,
  CONTENTS_SIZE 		NUMBER(10) 			NULL,
  
  CONTAINER_OID			VARCHAR2(11)		NULL,
  INPUT_USER			VARCHAR2(11)		NULL,
  CONTENTS_TITLE        VARCHAR2(255)       NULL,
  ORDER_NO              NUMBER(5)           NULL,
  CONSTRAINT TS02_TB_CONTENTS PRIMARY KEY(OID)
);

COMMENT ON TABLE TS02_TB_CONTENTS IS '컨텐츠 테이블';

COMMENT ON COLUMN TS02_TB_CONTENTS.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_CONTENTS.TARGET_OBJECT IS '타겟 Object 해당객체의 getObjectType';
COMMENT ON COLUMN TS02_TB_CONTENTS.TARGET_OID IS '타겟 OID';
COMMENT ON COLUMN TS02_TB_CONTENTS.CONTENTS IS '컨텐츠';
COMMENT ON COLUMN TS02_TB_CONTENTS.CONTENTS_SIZE IS '컨텐츠 사이즈';

COMMENT ON COLUMN TS02_TB_CONTENTS.CONTAINER_OID IS '컨테이너 OID - Posting일 경우 boardOid';
COMMENT ON COLUMN TS02_TB_CONTENTS.INPUT_USER IS '등록자 - 통계를 위해';
COMMENT ON COLUMN TS02_TB_CONTENTS.CONTENTS_TITLE IS '컨텐츠 제목';
COMMENT ON COLUMN TS02_TB_CONTENTS.ORDER_NO IS '컨텐츠 순서(하나의 타겟에 다수의 컨텐츠 사용 시)';


---------------------------------------------------------------
-- TS02_TB_POSTING  : 게시물 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_POSTING (
  OID 									VARCHAR2(11) 			NOT NULL,
  BOARD_OID 							VARCHAR2(11) 			NULL,
  NOTICE_LEVEL							NUMBER(3)				DEFAULT 0 NULL,
  TEMP_YN 								CHAR(1) 				NULL,
  
  FROM_DATE 							DATE 								NULL,
  TO_DATE 								DATE 								NULL,
  DEL_USER 								VARCHAR2(11) 			NULL,
  DEL_DATE 								DATE 					NULL,

  THREAD_OID 							VARCHAR2(11) 			NULL,
  THREAD_FULL_PATH_OID 					VARCHAR2(700) 			NULL,
  THREAD_PARENT_OID 					VARCHAR2(11) 			NULL,
  THREAD_DEPTH 							NUMBER(5)				NULL,
  THREAD_ORDER_NO 						NUMBER(5)				NULL,
  
  RE_CNT 								NUMBER(10)  			DEFAULT '0' NULL,
  CMT_CNT 								NUMBER(10) 				DEFAULT '0' NULL,
  RCMD_CNT 								NUMBER(10) 				DEFAULT '0' NULL,
  LIKE_CNT 								NUMBER(10) 				DEFAULT '0' NULL,
  VIEW_CNT								NUMBER(10)  			DEFAULT '0' NULL,
  
  ANONYMOUS_PWD 						VARCHAR2(255) 			NULL,
  PICK_YN 								CHAR(1) 				DEFAULT 'N' NULL,
  
  CUSTOM_FIELD1 						VARCHAR2(255) 			NULL,
  CUSTOM_FIELD2 						VARCHAR2(255) 			NULL,
  CUSTOM_FIELD3 						VARCHAR2(255) 			NULL,
  CUSTOM_FIELD4 						VARCHAR2(255) 			NULL,
  CUSTOM_FIELD5 						VARCHAR2(255) 			NULL,
  CONSTRAINT TS02_TB_POSTING PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_POSTING IS '포스팅 테이블';

COMMENT ON COLUMN TS02_TB_POSTING.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_POSTING.BOARD_OID IS 'BOARD OID';
COMMENT ON COLUMN TS02_TB_POSTING.NOTICE_LEVEL IS '공지 레벨 1-일반공지, 2-필수';
COMMENT ON COLUMN TS02_TB_POSTING.TEMP_YN IS '임시저장 여부';

COMMENT ON COLUMN TS02_TB_POSTING.FROM_DATE IS '공지 시작일';
COMMENT ON COLUMN TS02_TB_POSTING.TO_DATE IS '공지 종료일';
COMMENT ON COLUMN TS02_TB_POSTING.DEL_USER IS '삭제자';
COMMENT ON COLUMN TS02_TB_POSTING.DEL_DATE IS '삭제일시';

COMMENT ON COLUMN TS02_TB_POSTING.THREAD_OID IS '스레드 OID - 답변시 사용';
COMMENT ON COLUMN TS02_TB_POSTING.THREAD_FULL_PATH_OID IS '스레드 전체 OID Path - 답변 삭제시 사용';
COMMENT ON COLUMN TS02_TB_POSTING.THREAD_PARENT_OID IS '스레드 부모 OID - 답변시 사용';
COMMENT ON COLUMN TS02_TB_POSTING.THREAD_DEPTH IS '스레드 단계 - 답변시 사용';
COMMENT ON COLUMN TS02_TB_POSTING.THREAD_ORDER_NO IS '스레드 정렬순서 - 답변시 사용';

COMMENT ON COLUMN TS02_TB_POSTING.RE_CNT IS '답글 카운트';
COMMENT ON COLUMN TS02_TB_POSTING.CMT_CNT IS '코멘트 카운트';
COMMENT ON COLUMN TS02_TB_POSTING.RCMD_CNT IS '추천 카운트';
COMMENT ON COLUMN TS02_TB_POSTING.LIKE_CNT IS '좋아요 카운트';
COMMENT ON COLUMN TS02_TB_POSTING.VIEW_CNT IS '조회 카운트';

COMMENT ON COLUMN TS02_TB_POSTING.ANONYMOUS_PWD IS '비밀글 비밀번호';
COMMENT ON COLUMN TS02_TB_POSTING.PICK_YN IS '채택여부';

COMMENT ON COLUMN TS02_TB_POSTING.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_TB_POSTING.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_TB_POSTING.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_TB_POSTING.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_TB_POSTING.CUSTOM_FIELD5 IS '커스텀 필드5';

---------------------------------------------------------------
-- TS02_TB_POSTING_LANG  : 게시물 다국어 테이블
---------------------------------------------------------------

CREATE TABLE TS02_TB_POSTING_LANG (	
   	OID 					VARCHAR2(11 BYTE) 		NOT NULL ENABLE, 
	LANG 					VARCHAR2(2 BYTE) 		NOT NULL ENABLE, 
	TITLE 					VARCHAR2(255 BYTE), 
	CONTENTS 				VARCHAR2(4000 BYTE), 
	
	INPUT_USER_INFO_LIST	VARCHAR2(500 BYTE),
	INPUT_USER 				VARCHAR2(11 BYTE), 
	INPUT_DATE 				DATE 					DEFAULT SYSDATE, 
	MOD_USER 				VARCHAR2(11 BYTE), 
	MOD_DATE 				DATE	 
   );

   COMMENT ON COLUMN TS02_TB_POSTING_LANG.OID IS 'OID';
   COMMENT ON COLUMN TS02_TB_POSTING_LANG.LANG IS 'LANG 한글 ko, 영어 en, 중국어 cn';
   COMMENT ON COLUMN TS02_TB_POSTING_LANG.TITLE IS '게시물 명';
   COMMENT ON COLUMN TS02_TB_POSTING_LANG.CONTENTS IS '게시물 내용';
   COMMENT ON COLUMN TS02_TB_POSTING_LANG.INPUT_USER IS '등록자';
   COMMENT ON COLUMN TS02_TB_POSTING_LANG.INPUT_DATE IS '등록일시';
   COMMENT ON COLUMN TS02_TB_POSTING_LANG.MOD_USER IS '수정자';
   COMMENT ON COLUMN TS02_TB_POSTING_LANG.MOD_DATE IS '수정일시';
   COMMENT ON TABLE TS02_TB_POSTING_LANG IS '게시물 다국어 테이블';

---------------------------------------------------------------
--  TS02_TB_POPUP : 팝업 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_POPUP (

                          OID 						VARCHAR2(11) 			NOT NULL,
                          PART_OID			 		VARCHAR2(11) 			NULL,
                          NAME 						VARCHAR2(255) 			NULL,
                          START_DATE 				DATE 					NULL,
                          END_DATE 					DATE 					NULL,

                          WIDTH 					NUMBER(5)			    NULL,
                          HEIGHT 					NUMBER(5)		        NULL,
                          POSITION_X           	 	NUMBER(5)               NULL,
                          POSITION_Y           		NUMBER(5)               NULL,
                          ORDER_NO					NUMBER(5)               NULL,

                          POPUP_CONTENTS_TYPE_FLAG 	CHAR(1)  				NULL,
                          POPUP_VIEW_TYPE_FLAG 	    CHAR(1)  				NULL,
                          LINK_URL 					VARCHAR2(255)			NULL,
                          LINK_TYPE_FLAG 			CHAR(1)					NULL,
                          CENTER_ALIGNMENT_YN       CHAR(1)                 NULL,

                          USE_YN		 			CHAR(1) 				DEFAULT 'Y' NULL,
                          INPUT_USER 				VARCHAR2(11) 			NULL,
                          INPUT_DATE 				TIMESTAMP 				NULL,

                          CUSTOM_FIELD1 			VARCHAR2(255) 			NULL,
                          CUSTOM_FIELD2 			VARCHAR2(255) 			NULL,
                          CUSTOM_FIELD3 			VARCHAR2(255) 			NULL,
                          CUSTOM_FIELD4 			VARCHAR2(255) 			NULL,
                          CUSTOM_FIELD5 			VARCHAR2(255) 			NULL,

                          CONSTRAINT TB_POPUP PRIMARY KEY  ( OID )
);

COMMENT ON TABLE TS02_TB_POPUP IS '팝업 테이블';

COMMENT ON COLUMN TS02_TB_POPUP.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_POPUP.PART_OID  IS '파트 OID';
COMMENT ON COLUMN TS02_TB_POPUP.NAME  IS '팝업명';
COMMENT ON COLUMN TS02_TB_POPUP.START_DATE IS '팝업 시작일';
COMMENT ON COLUMN TS02_TB_POPUP.END_DATE IS '팝업 종료일';

COMMENT ON COLUMN TS02_TB_POPUP.WIDTH IS '팝업 넓이';
COMMENT ON COLUMN TS02_TB_POPUP.HEIGHT IS '팝업 높이';
COMMENT ON COLUMN TS02_TB_POPUP.POSITION_X IS '가로 위치';
COMMENT ON COLUMN TS02_TB_POPUP.POSITION_Y IS '세로 위치';
COMMENT ON COLUMN TS02_TB_POPUP.ORDER_NO IS '정렬 순서';

COMMENT ON COLUMN TS02_TB_POPUP.POPUP_CONTENTS_TYPE_FLAG IS '팝업 콘텐츠 타입  ex) 이미지 팝업 - dropzone(I), 본문 팝업 - editor(C)';
COMMENT ON COLUMN TS02_TB_POPUP.POPUP_VIEW_TYPE_FLAG IS '팝업 보기 타입  ex) 리스트 타입(L), 일반 타입(G) - 위치, 사이즈 지정';
COMMENT ON COLUMN TS02_TB_POPUP.LINK_URL IS '연결 URL';
COMMENT ON COLUMN TS02_TB_POPUP.LINK_TYPE_FLAG IS '링크 타입 (새창 띄우기(N), 페이지 이동(P))';
COMMENT ON COLUMN TS02_TB_POPUP.CENTER_ALIGNMENT_YN IS '가운데 정렬 적용 여부';

COMMENT ON COLUMN TS02_TB_POPUP.USE_YN IS 'Y 사용중, N 사용안함';
COMMENT ON COLUMN TS02_TB_POPUP.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_POPUP.INPUT_DATE IS '등록일';

COMMENT ON COLUMN TS02_TB_POPUP.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_TB_POPUP.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_TB_POPUP.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_TB_POPUP.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_TB_POPUP.CUSTOM_FIELD5 IS '커스텀 필드5';