--  TS02_AM_DATASHEET : Datasheet 테이블
DROP TABLE TS02_AM_DATASHEET;

--  TS02_AM_DATASHEET_ITEM : Datasheet 항목 테이블
DROP TABLE TS02_AM_DATASHEET_ITEM;

--  TS02_AM_DATASHEET_TARGET_ITEM : Datasheet 타겟의 Datasheet 항목 테이블
DROP TABLE TS02_AM_DATASHEET_TARGET_ITEM;