---------------------------------------------------------------
-- TS02_TB_FILE : 파일 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_FILE (
  OID 					VARCHAR2(11) 		 NOT NULL,
  STORAGE_FILE_UID 		VARCHAR2(20) 		 NOT NULL,
  FILE_TYPE 			VARCHAR2(8) 		 NULL,
  TARGET_OBJECT 		VARCHAR2(4) 		 NULL,
  TARGET_OID 			VARCHAR2(11) 		 NULL,

  CONTAINER_OID			VARCHAR2(11)		 NULL,
  FILE_NAME 			VARCHAR2(255) 		 NULL,
  FILE_SIZE 			NUMBER(10,2) 		 NULL,
  FILE_EXT 				VARCHAR2(10) 		 NULL,
  FILE_URL 				VARCHAR2(255) 		 NULL,

  FILE_PLAY_TIME		DATE				 NULL,
  USE_YN 				CHAR(1) DEFAULT 'Y'	 NULL,
  THUMB_YN 				CHAR(1) DEFAULT 'N'  NULL,
  INPUT_USER 			VARCHAR2(11) 		 NULL,
  INPUT_DATE 			DATE DEFAULT SYSDATE NOT NULL,

  ORDER_NO 				NUMBER(10) 		 	 NULL,

  CUSTOM_FIELD1 		VARCHAR2(255) 	 	 NULL,
  CUSTOM_FIELD2 		VARCHAR2(255) 	 	 NULL,
  CUSTOM_FIELD3 		VARCHAR2(255) 	 	 NULL,
  CUSTOM_FIELD4 		VARCHAR2(255) 	 	 NULL,
  CUSTOM_FIELD5 		VARCHAR2(255) 	 	 NULL,
  CONSTRAINT TS02_TB_FILE PRIMARY KEY(OID)
);


COMMENT ON TABLE TS02_TB_FILE IS '파일 테이블';

COMMENT ON COLUMN TS02_TB_FILE.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_FILE.STORAGE_FILE_UID IS 'Storage File UID';
COMMENT ON COLUMN TS02_TB_FILE.FILE_TYPE IS '내부파일 타입, 타겟타입에 여러유형의 파일이 있을경우 사용';
COMMENT ON COLUMN TS02_TB_FILE.TARGET_OBJECT IS '타겟 객체';
COMMENT ON COLUMN TS02_TB_FILE.TARGET_OID IS '타겟 OID';

COMMENT ON COLUMN TS02_TB_FILE.CONTAINER_OID IS '컨테이너 OID - Posting일 경우 boardOid';
COMMENT ON COLUMN TS02_TB_FILE.FILE_NAME IS '파일명';
COMMENT ON COLUMN TS02_TB_FILE.FILE_SIZE IS '파일 사이즈';
COMMENT ON COLUMN TS02_TB_FILE.FILE_EXT IS '파일 확장자';
COMMENT ON COLUMN TS02_TB_FILE.USE_YN IS '사용여부';

COMMENT ON COLUMN TS02_TB_FILE.FILE_URL IS '파일 URL';
COMMENT ON COLUMN TS02_TB_FILE.FILE_PLAY_TIME IS '파일 재생시간';
COMMENT ON COLUMN TS02_TB_FILE.THUMB_YN IS '썸네일여부';
COMMENT ON COLUMN TS02_TB_FILE.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_FILE.INPUT_DATE IS '등록일시';
COMMENT ON COLUMN TS02_TB_FILE.ORDER_NO IS '파일 업로드 순서';

COMMENT ON COLUMN TS02_TB_FILE.CUSTOM_FIELD1 IS '커스텀필드1';
COMMENT ON COLUMN TS02_TB_FILE.CUSTOM_FIELD2 IS '커스텀필드2';
COMMENT ON COLUMN TS02_TB_FILE.CUSTOM_FIELD3 IS '커스텀필드3';
COMMENT ON COLUMN TS02_TB_FILE.CUSTOM_FIELD4 IS '커스텀필드4';
COMMENT ON COLUMN TS02_TB_FILE.CUSTOM_FIELD5 IS '커스텀필드5';



---------------------------------------------------------------
-- TS02_TB_STORAGE_FILE : 스토리지 파일 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_STORAGE_FILE (

  STORAGE_FILE_UID 	VARCHAR2(20) 			NOT NULL,
  HASH_VALUE 		VARCHAR2(50) 			NULL,
  FILE_CNT			NUMBER(10)				NULL,
  CUSTOM_FIELD1		VARCHAR2(255) 	 		NULL,
  CUSTOM_FIELD2		VARCHAR2(255) 	 		NULL,
  CUSTOM_FIELD3		VARCHAR2(255) 	 		NULL,
  INPUT_DATE 		DATE 					NULL,
  CONSTRAINT TS02_TB_STORAGE_FILE PRIMARY KEY(STORAGE_FILE_UID)
);

COMMENT ON TABLE TS02_TB_STORAGE_FILE IS '스토리지 파일 테이블';

COMMENT ON COLUMN TS02_TB_STORAGE_FILE.STORAGE_FILE_UID IS 'Storage File UID';
COMMENT ON COLUMN TS02_TB_STORAGE_FILE.HASH_VALUE IS 'HASH 값';
COMMENT ON COLUMN TS02_TB_STORAGE_FILE.FILE_CNT IS '해당 스토리지를 사용하는 파일 카운트';
COMMENT ON COLUMN TS02_TB_STORAGE_FILE.CUSTOM_FIELD1 IS '커스텀필드1';
COMMENT ON COLUMN TS02_TB_STORAGE_FILE.CUSTOM_FIELD2 IS '커스텀필드2';
COMMENT ON COLUMN TS02_TB_STORAGE_FILE.CUSTOM_FIELD3 IS '커스텀필드3';
COMMENT ON COLUMN TS02_TB_STORAGE_FILE.INPUT_DATE IS '등록일시';



---------------------------------------------------------------
-- TS02_TB_THUMBNAIL : 썸네일 파일 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_THUMBNAIL (
  OID 					VARCHAR2(11) 				NOT NULL,
  TARGET_OBJECT 		VARCHAR2(4) 				NULL,
  TARGET_OID 			VARCHAR2(11) 				NULL,
  STORAGE_FILE_UID   	VARCHAR2(20) 				NOT NULL,
  THUMBNAIL_TYPE  		VARCHAR2(8) 				NULL,
  
  THUMBNAIL_BASE64   	CLOB 						NULL,
  USE_YN				CHAR(1)						NOT NULL,
  INPUT_USER 			VARCHAR2(11)  				NULL,
  INPUT_DATE 			DATE 						NOT NULL,
  CONSTRAINT TS02_TB_THUMBNAIL PRIMARY KEY  ( OID )
);

COMMENT ON TABLE TS02_TB_THUMBNAIL IS '썸네일 파일 관계 테이블';

COMMENT ON COLUMN TS02_TB_THUMBNAIL.OID IS '썸네일 파일 관계 테이블 oid';
COMMENT ON COLUMN TS02_TB_THUMBNAIL.TARGET_OBJECT IS '타겟 객체';
COMMENT ON COLUMN TS02_TB_THUMBNAIL.TARGET_OID IS '타겟 oid';
COMMENT ON COLUMN TS02_TB_THUMBNAIL.STORAGE_FILE_UID IS 'Storage File UID';
COMMENT ON COLUMN TS02_TB_THUMBNAIL.THUMBNAIL_TYPE IS '썸네일 사용구분';

COMMENT ON COLUMN TS02_TB_THUMBNAIL.THUMBNAIL_BASE64 IS '썸네일 이미지 base64 데이터';
COMMENT ON COLUMN TS02_TB_THUMBNAIL.USE_YN IS '사용여부';
COMMENT ON COLUMN TS02_TB_THUMBNAIL.INPUT_USER IS '등록 사용자 oid';
COMMENT ON COLUMN TS02_TB_THUMBNAIL.INPUT_DATE IS '등록 일시';






