---------------------------------------------------------------
--  TS02_AM_ONE_TO_ONE : 1대1 문의 테이블
---------------------------------------------------------------
CREATE TABLE TS02_AM_ONE_TO_ONE
(
    OID                 VARCHAR2(11)        	NOT NULL,
    TITLE               VARCHAR2(255)       	NULL,
    CONFIG_OID          VARCHAR2(11)        	NULL,
    INPUT_USER          VARCHAR2(11)        	NULL,
    INPUT_DATE          DATE DEFAULT SYSDATE	NULL,

    DESCR               VARCHAR2(4000)      NULL,
    RECEIVER_EMAIL      VARCHAR2(500)       NULL,

    CUSTOM_FIELD1       VARCHAR2(255)       NULL,
    CUSTOM_FIELD2       VARCHAR2(255)       NULL,
    CUSTOM_FIELD3       VARCHAR2(255)       NULL,
    CUSTOM_FIELD4       VARCHAR2(255)       NULL,
    CUSTOM_FIELD5       VARCHAR2(255)       NULL,

    CONSTRAINT TS02_AM_ONE_TO_ONE PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_AM_ONE_TO_ONE IS '1대1 문의 테이블';

COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.OID IS 'OID';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.TITLE IS '제목';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.CONFIG_OID IS '문의 설정 OID';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.INPUT_USER IS '문의자 OID';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.INPUT_DATE IS '문의일시';

COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.DESCR IS '설명';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.RECEIVER_EMAIL IS '수신자 이메일';

COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE.CUSTOM_FIELD5 IS '커스텀 필드5';



---------------------------------------------------------------
--  TS02_AM_ONE_TO_ONE_DETAIL : 1대1 문의 상세정보 테이블
---------------------------------------------------------------
CREATE TABLE TS02_AM_ONE_TO_ONE_DETAIL
(
    OID                 VARCHAR2(11)        NOT NULL,
    OTO_OID             VARCHAR2(11)        NOT NULL,
    DETAIL_TYPE         VARCHAR2(8)         NULL,
    DETAIL_QUESTION     VARCHAR2(255)       NULL,
    DETAIL_ANSWER       VARCHAR2(255)       NULL,
    CONSTRAINT TS02_AM_ONE_TO_ONE_DETAIL PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_AM_ONE_TO_ONE_DETAIL IS '1대1 문의 상세정보 테이블';

COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_DETAIL.OID IS 'OID';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_DETAIL.OTO_OID IS '1대1 문의 OID';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_DETAIL.DETAIL_TYPE IS '상세정보 타입(추가문의, 수신자 이메일)';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_DETAIL.DETAIL_QUESTION IS '문의 질문';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_DETAIL.DETAIL_ANSWER IS '문의 답변';

---------------------------------------------------------------
--  TS02_AM_ONE_TO_ONE_CONFIG : 1대1 문의 설정정보 테이블
---------------------------------------------------------------
CREATE TABLE TS02_AM_ONE_TO_ONE_CONFIG
(
    OID                             VARCHAR2(11)    NOT NULL,
    PARENT_OID                      VARCHAR2(11)    NULL,
    CONFIG_TYPE                     VARCHAR2(8)     NULL,
    CONFIG_QUESTION                 VARCHAR2(255)   NULL,
    CONFIG_ANSWER                   VARCHAR2(255)   NULL,
    
    CONFIG_RECEIVER_EMAIL           VARCHAR2(255)   NULL,
    CONSTRAINT TS02_AM_ONE_TO_ONE_CONFIG PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_AM_ONE_TO_ONE_CONFIG IS '1대1 문의 설정 상세정보 테이블';

COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_CONFIG.OID IS 'OID';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_CONFIG.PARENT_OID IS '1대1 문의 부모 설정정보 OID';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_CONFIG.CONFIG_TYPE IS '설정 타입';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_CONFIG.CONFIG_QUESTION IS '설정 질문';
COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_CONFIG.CONFIG_ANSWER IS '설정 답변';

COMMENT ON COLUMN TS02_AM_ONE_TO_ONE_CONFIG.CONFIG_RECEIVER_EMAIL IS '설정 이메일';