
-- TS02_TB_MSG_BOOKING : 메시지 예약 테이블
DROP TABLE TS02_TB_MSG_BOOKING;

-- TS02_TB_MSG_GROUP  : 메시지 그룹 테이블
DROP TABLE TS02_TB_MSG_GROUP;

-- TS02_TB_MSG_GROUP_USER_REL : 메시지 그룹 관계테이블 - 메시지그룹에 속한 사용자 관리
DROP TABLE TS02_TB_MSG_GROUP_REL;


-- TS02_TB_MSG: 메시지 테이블
DROP TABLE TS02_TB_MSG;


-- TS02_TB_MSG_SEND_RESULT : 메시지 발송 결과 테이블  추가
DROP TABLE TS02_TB_MSG_SEND_HIST;


-- TS02_TB_MSG_SEND_HIST : 메시지 발신 이력테이블 
DROP TABLE TS02_TB_MSG_SEND_HIST;


-- TS02_TB_MSG_TEMPLATE : 메시지 템플릿 테이블 
DROP TABLE TS02_TB_MSG_TEMPLATE;

-- TS02_TB_MSG_TEMPLATE_ITEM : 메시지 템플릿 아이템 테이블
DROP TABLE TS02_TB_MSG_TEMPLATE_ITEM;