CREATE TABLE TS02_AM_DOC_SHARE_AUDIT
(
    OID		        VARCHAR2(11 BYTE)		NOT NULL,
    TARGET_OID_LIST	VARCHAR2(4000 BYTE)		NULL,
    EMAIL		    VARCHAR2(50 BYTE)		NULL,
    INPUT_DATE 	    DATE DEFAULT SYSDATE    NOT NULL,
    SHARE_TYPE	    VARCHAR2(8)		        NULL,

    ACCESS_URL      VARCHAR2(1000)          NULL,
    USER_IP         VARCHAR2(20)            NULL
);

COMMENT ON TABLE TS02_AM_DOC_SHARE_AUDIT IS '문서 공유/다운 로그 테이블';

COMMENT ON COLUMN TS02_AM_DOC_SHARE_AUDIT.OID IS '문서 공유/다운 로그 테이블 OID';
COMMENT ON COLUMN TS02_AM_DOC_SHARE_AUDIT.TARGET_OID_LIST IS 'TARGET OID 리스트';
COMMENT ON COLUMN TS02_AM_DOC_SHARE_AUDIT.EMAIL IS '공유/다운 이용자 EMAIL';
COMMENT ON COLUMN TS02_AM_DOC_SHARE_AUDIT.INPUT_DATE IS '등록일시';
COMMENT ON COLUMN TS02_AM_DOC_SHARE_AUDIT.SHARE_TYPE IS '문서공유/다운 타입';

COMMENT ON COLUMN TS02_AM_DOC_SHARE_AUDIT.ACCESS_URL IS '접근 URL';
COMMENT ON COLUMN TS02_AM_DOC_SHARE_AUDIT.USER_IP IS '사용자 IP';