---------------------------------------------------------------
-- TS02_TB_RELATIONSHIP : 관련정보 연결 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_RELATIONSHIP (
  OID 						VARCHAR2(11) 			NOT NULL,
  OBJECT 					VARCHAR2(4) 			NOT NULL,
  RELATIONSHIP_OID 			VARCHAR2(11) 			NOT NULL,
  RELATIONSHIP_OBJECT 		VARCHAR2(4) 			NOT NULL,
  RELATIONSHIP_TYPE 		VARCHAR2(8) 			NOT NULL,

  INPUT_DATE 			DATE DEFAULT SYSDATE 		NOT NULL,
  CONSTRAINT TS02_TB_RELATIONSHIP PRIMARY KEY( OID, RELATIONSHIP_OID )
);

COMMENT ON TABLE TS02_TB_RELATIONSHIP IS '관련정보 테이블';

COMMENT ON COLUMN TS02_TB_RELATIONSHIP.OID IS '관련정보 기준 OID';
COMMENT ON COLUMN TS02_TB_RELATIONSHIP.OBJECT IS '관련정보 기준 객체';
COMMENT ON COLUMN TS02_TB_RELATIONSHIP.RELATIONSHIP_OID IS '관련정보 OID';
COMMENT ON COLUMN TS02_TB_RELATIONSHIP.RELATIONSHIP_OBJECT IS '관련정보 객체';
COMMENT ON COLUMN TS02_TB_RELATIONSHIP.RELATIONSHIP_TYPE IS '관련 정보 타입(관련 게시글, 관련 앱, 관련 댓글 등)';

COMMENT ON COLUMN TS02_TB_RELATIONSHIP.INPUT_DATE IS '등록일시';

