-- 소재 구분 중국어 기본값
INSERT INTO TS02_AM_MATERIAL_LANG
( OID, LANG, NAME, CLASS_NAME, DESCR, INPUT_USER, INPUT_DATE)
SELECT OID, 'CN', NAME || '-CN', CLASS_NAME || '-CN', DESCR || '-CN', INPUT_USER, INPUT_DATE FROM TS02_AM_MATERIAL_LANG WHERE LANG = 'KO';
-- 소재 구분 영어 기본값
INSERT INTO TS02_AM_MATERIAL_LANG
( OID, LANG, NAME, CLASS_NAME, DESCR, INPUT_USER, INPUT_DATE)
SELECT OID, 'EN', NAME || '-EN', CLASS_NAME || '-EN', DESCR || '-EN', INPUT_USER, INPUT_DATE FROM TS02_AM_MATERIAL_LANG WHERE LANG = 'KO';

-- 카테고리 중국어 기본값
INSERT INTO TS02_TB_CATEGORY_LANG
( OID, LANG, NAME, DESCR, INPUT_USER, INPUT_DATE)
SELECT OID, 'CN', NAME || '-CN', DESCR || '-CN', INPUT_USER, INPUT_DATE FROM TS02_TB_CATEGORY_LANG WHERE LANG = 'KO';
-- 카테고리 영어 기본값
INSERT INTO TS02_TB_CATEGORY_LANG
( OID, LANG, NAME, DESCR, INPUT_USER, INPUT_DATE)
SELECT OID, 'EN', NAME || '-EN', DESCR || '-EN', INPUT_USER, INPUT_DATE FROM TS02_TB_CATEGORY_LANG WHERE LANG = 'KO';

-- 제품 중국어 기본값
INSERT INTO TS02_AM_PRODUCT_LANG
( OID, LANG, NAME, DESCR, INPUT_USER, INPUT_DATE)
SELECT OID, 'CN', NAME || '-CN', DESCR || '-CN', INPUT_USER, INPUT_DATE FROM TS02_AM_PRODUCT_LANG WHERE LANG = 'KO';
-- 제품 영어 기본값
INSERT INTO TS02_AM_PRODUCT_LANG
( OID, LANG, NAME, DESCR, INPUT_USER, INPUT_DATE)
SELECT OID, 'EN', NAME || '-EN', DESCR || '-EN', INPUT_USER, INPUT_DATE FROM TS02_AM_PRODUCT_LANG WHERE LANG = 'KO';

-- 포스팅 중국어 기본값
INSERT INTO TS02_TB_POSTING_LANG
( OID, LANG, TITLE, CONTENTS, INPUT_USER_INFO_LIST , INPUT_USER, INPUT_DATE)
SELECT OID, 'CN', TITLE || '-CN', CONTENTS || '-CN', INPUT_USER_INFO_LIST, INPUT_USER, INPUT_DATE FROM TS02_TB_POSTING_LANG WHERE LANG = 'KO';
-- 포스팅 영어 기본값
INSERT INTO TS02_TB_POSTING_LANG
( OID, LANG, TITLE, CONTENTS, INPUT_USER_INFO_LIST, INPUT_USER, INPUT_DATE)
SELECT OID, 'EN', TITLE || '-EN', CONTENTS || '-EN', INPUT_USER_INFO_LIST, INPUT_USER, INPUT_DATE FROM TS02_TB_POSTING_LANG WHERE LANG = 'KO';