--  TS02_AM_ONE_TO_ONE : 1대1 문의 테이블
DROP TABLE TS02_AM_ONE_TO_ONE;

--  TS02_AM_ONE_TO_ONE_DETAIL : 1대1 문의 상세정보 테이블
DROP TABLE TS02_AM_ONE_TO_ONE_DETAIL;

--  TS02_AM_ONE_TO_ONE_CONFIG : 1대1 문의 설정 테이블
DROP TABLE TS02_AM_ONE_TO_ONE_CONFIG;

--  TS02_AM_ONE_TO_ONE_CONFIG_DETAIL : 1대1 문의 설정 상세정보 테이블
DROP TABLE TS02_AM_ONE_TO_ONE_CONFIG_DETAIL;