INSERT INTO TS02_TB_POSTING_LANG
( OID, LANG, TITLE, CONTENTS, INPUT_USER_INFO_LIST, INPUT_USER, INPUT_DATE )
SELECT OID, 'KO',TITLE, (SELECT CONTENTS FROM TS02_TB_CONTENTS WHERE TARGET_OID = P.OID AND TARGET_OBJECT = 'FWPO' ), 
INPUT_USER_INFO_LIST, INPUT_USER, INPUT_DATE  
FROM TS02_TB_POSTING P;


-- 백업용 생성
CREATE TABLE TS02_TB_POSTING_BACKUP
AS
SELECT * FROM TS02_TB_POSTING;




-- 실제는 제일 나중에 작업 다 한후에 작업처리할 것.
-- TS02_TB_POSTING 에서 TS02_TB_POSTING_LANG에 있는 컬럼 제거
ALTER TABLE TS02_TB_POSTING DROP COLUMN TITLE;
ALTER TABLE TS02_TB_POSTING DROP COLUMN INPUT_USER_INFO_LIST;
ALTER TABLE TS02_TB_POSTING DROP COLUMN INPUT_USER;
ALTER TABLE TS02_TB_POSTING DROP COLUMN INPUT_DATE;
ALTER TABLE TS02_TB_POSTING DROP COLUMN MOD_USER;
ALTER TABLE TS02_TB_POSTING DROP COLUMN MOD_DATE;