-- TS02_TB_PART 데이터 TS02_AM_MATERIAL 및 TS02_AM_MATERIAL_LANG 테이블에 INSERT
INSERT INTO TS02_AM_MATERIAL
( OID, SYSTEM_OID )
SELECT OID, SYSTEM_OID FROM TS02_TB_PART;

INSERT INTO TS02_AM_MATERIAL_LANG
( OID, LANG, NAME, CLASS_NAME, INPUT_USER, INPUT_DATE)
SELECT OID, 'KO', NAME, CLASS_NAME, INPUT_USER, INPUT_DATE FROM TS02_TB_PART;

-- TS02_TB_CONTENTS 테이블에 있던 상세 정보 TS02_AM_MATERIAL_LANG에 UPDATE
UPDATE TS02_AM_MATERIAL_LANG L SET DESCR  =
(
SELECT CONTENTS FROM TS02_TB_CONTENTS C
WHERE C.TARGET_OID = L.OID
);
