---------------------------------------------------------------
-- TS02_TB_DRAW_CELL : 표 그리기 좌표값 정보 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_DRAW_CELL (

  OID 	            VARCHAR2(11) 			NOT NULL,
  TARGET_OID 		VARCHAR2(11) 			NULL,
  X_LOC			    VARCHAR2(20)			NULL,
  Y_LOC		        VARCHAR2(20) 	 		NULL,
  MERGE_SIZE		VARCHAR2(100) 	 		NULL,

  MERGE_DIRECTION	VARCHAR2(1) 	 		NULL,
  CONSTRAINT TS02_TB_DRAW_CELL PRIMARY KEY(OID)
);

COMMENT ON TABLE TS02_TB_DRAW_CELL IS '표 그리기 좌표값 정보 테이블';

COMMENT ON COLUMN TS02_TB_DRAW_CELL.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_DRAW_CELL.TARGET_OID IS '타겟 OID';
COMMENT ON COLUMN TS02_TB_DRAW_CELL.X_LOC IS 'X 좌표';
COMMENT ON COLUMN TS02_TB_DRAW_CELL.Y_LOC IS 'Y 좌표';
COMMENT ON COLUMN TS02_TB_DRAW_CELL.MERGE_SIZE IS '병합 크기';

COMMENT ON COLUMN TS02_TB_DRAW_CELL.MERGE_DIRECTION IS '병합 방향';
