---------------------------------------------------------------
--  기기와 사용자 뷰, 추후 필요 시 생성
-- 사용 테이블 : TS02_TB_DEVICE, TS02_TB_USER_DEVICE_REL, TS02_TB_USER
---------------------------------------------------------------
CREATE OR REPLACE VIEW VS02_USER_DEVICE AS
SELECT
	   D.OID AS OID,
       D.DEVICE_MODEL_NAME AS DEVICE_MODEL_NAME,
       D.SERIAL_NUM AS SERIAL_NUM,
       D.PUSH_TOKEN AS PUSH_TOKEN,
       D.PUSH_YN AS PUSH_YN,

       D.IMEI AS IMEI,
       D.BUILD_VERSION AS BUILD_VERSION,
       D.OS_TYPE_FLAG AS OS_TYPE_FLAG,
       D.APP_VERSION AS APP_VERSION,
       D.OS_VERSION AS OS_VERSION,

       D.UUID AS UUID,
       D.INPUT_DATE AS INPUT_DATE,

       USR.OID AS USER_OID,
       USR.USER_ID AS USER_ID,
       USR.NAME AS USER_NAME,
       USR.PWD AS USER_PWD,
       USR.EMAIL AS USER_EMAIL,

       USR.TEL_PART1 AS USER_TEL_PART1,
       USR.TEL_PART2 AS USER_TEL_PART2,
       USR.TEL_PART3 AS USER_TEL_PART3,
       USR.PHONE_PART1 AS USER_PHONE_PART1,
       USR.PHONE_PART2 AS USER_PHONE_PART2,
       USR.PHONE_PART3 AS USER_PHONE_PART3,

       USR.NICK AS USER_NICK,
       USR.BIRTH_YEAR AS USER_YEAR,
       USR.BIRTH_MONTH AS USER_MONTH,
       USR.BIRTH_DAY AS USER_DAY,

       USR.POST_CODE AS USER_POST_CODE,
       USR.ADDR_PART1 AS USER_ADD_PART1,
       USR.ADDR_PART2 AS USER_ADDR_PART2,
       USR.STATUS_TYPE_FLAG AS USER_STATUS_TYPE_FLAG,
       USR.JOIN_TYPE AS USER_JOIN_TYPE,

       USR.GROUP_OID AS USER_GROUP_OID,
       USR.RANK AS USER_RANK,
       USR.INPUT_USER AS USER_INPUT_USER,
       USR.INPUT_DATE AS USER_INPUT_DATE,
       USR.HIRE_DATE AS USER_HIRE_DATE,

       USR.RETIRE_DATE AS USER_RETIRE_DATE,
       USR.DESCR AS USER_DESCR,
       USR.EMP_NO AS USER_EMP_NO,
       DREL.USE_YN AS REL_USE_YN
FROM TS02_TB_DEVICE D
     JOIN TS02_TB_USER_DEVICE_REL DREL
     ON D.UUID = DREL.UUID
     JOIN TS02_TB_USER USR
     ON DREL.USER_OID = USR.OID;


---------------------------------------------------------------
-- 유저 - 권한 뷰
-- 사용 테이블 : TS02_TB_DEVICE, TS02_TB_USER_DEVICE_REL, TS02_TB_USER
---------------------------------------------------------------
CREATE OR REPLACE VIEW VS02_USER_ROLE AS
SELECT
    U.OID OID,
    U.USER_ID,
    U.NAME,
    U.EMAIL,

    U.STATUS_TYPE_FLAG,
    U.USER_TYPE,
    U.COMPANY_OID,

    U.GROUP_OID,
    U.BRANCH_OID,
    U.RANK,
    U.POSITION,

    U.INPUT_DATE,
    U.CUSTOM_FIELD1,
    U.CUSTOM_FIELD2,

    U.TEL_PART1,
    U.TEL_PART2,
    U.TEL_PART3,
    U.PHONE_PART1,
    U.PHONE_PART2,
    U.PHONE_PART3,
    U.JOIN_PATH_DESCR,

    R.OID ROLE_OID,
    R.ROLE_NAME,

    REL.TARGET_OBJECT,
    REL.ROLE_START_DATE ROLE_START_DATE,
    REL.ROLE_END_DATE ROLE_END_DATE
FROM TS02_TB_USER U
         JOIN TS02_TB_ROLE_USER_REL REL
              ON U.OID = REL.TARGET_OID
                  AND REL.TARGET_OBJECT  = 'FWUR'
         JOIN TS02_TB_ROLE R
              ON REL.ROLE_OID = R.OID;
