---------------------------------------------------------------
-- TS02_TB_BRANCH : 지점 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_BRANCH (
	OID 			VARCHAR2(11) 	NOT NULL,
	COMPANY_OID 	VARCHAR2(11) 	NULL,
	AREA_CODE       VARCHAR2(8)     NULL,
	OWNER 			VARCHAR2(11) 	NULL,
	NAME 			VARCHAR2(255) 	NULL,

    ADDR            VARCHAR2(500)   NULL,
    POST_CODE       VARCHAR2(25)     NULL,
    TEL             VARCHAR2(25)    NULL,
	DESCR 			VARCHAR2(500) 	NULL,

	INPUT_USER 		VARCHAR2(11) 	NULL,
  	INPUT_DATE 		DATE DEFAULT SYSDATE NOT NULL,
	ORDER_NO 		NUMBER(5) 		NULL,
	CONSTRAINT TS02_TB_BRANCH PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_BRANCH IS '지점 테이블';

COMMENT ON COLUMN TS02_TB_BRANCH.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_BRANCH.COMPANY_OID IS '회사 OID';
COMMENT ON COLUMN TS02_TB_BRANCH.AREA_CODE IS '지역 코드';
COMMENT ON COLUMN TS02_TB_BRANCH.OWNER IS '오너';
COMMENT ON COLUMN TS02_TB_BRANCH.NAME IS '지점명';

COMMENT ON COLUMN TS02_TB_BRANCH.ADDR IS '주소';
COMMENT ON COLUMN TS02_TB_BRANCH.POST_CODE IS '우편번호';
COMMENT ON COLUMN TS02_TB_BRANCH.TEL IS '전화번호';
COMMENT ON COLUMN TS02_TB_BRANCH.DESCR IS '비고';

COMMENT ON COLUMN TS02_TB_BRANCH.INPUT_USER IS '등록자 OID';
COMMENT ON COLUMN TS02_TB_BRANCH.INPUT_DATE IS '등록일';
COMMENT ON COLUMN TS02_TB_BRANCH.ORDER_NO IS '정렬순서';



---------------------------------------------------------------
-- TS02_TB_COMPANY : 회사 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_COMPANY (
    OID 			VARCHAR2(11) 	NOT NULL,
    BUSINESS 		VARCHAR2(255) 	NULL,
    COMPANY_NAME 	VARCHAR2(255) 	NULL,
    OWNER_NAME 		VARCHAR2(255) 	NULL,
    COMPANY_NO 		VARCHAR2(20) 	NULL,

    TEL_PART1 		VARCHAR2(4) 	NULL,
    TEL_PART2 		VARCHAR2(4) 	NULL,
    TEL_PART3 		VARCHAR2(4) 	NULL,
    POST_CODE 		VARCHAR2(7) 	NULL,
    ADDR_PART1 		VARCHAR2(500) 	NULL,

    ADDR_PART2 		VARCHAR2(500) 	NULL,
    DESCR 			VARCHAR2(500) 	NULL,
    INPUT_USER 		VARCHAR2(11) 	NULL,
    INPUT_DATE 		DATE 			NULL,
    ORDER_NO 		NUMBER(5) 		NULL,

    CONSTRAINT TS02_TB_COMPANY PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_COMPANY IS '회사 테이블';

COMMENT ON COLUMN TS02_TB_COMPANY.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_COMPANY.BUSINESS IS '업종';
COMMENT ON COLUMN TS02_TB_COMPANY.COMPANY_NAME IS '회사명';
COMMENT ON COLUMN TS02_TB_COMPANY.OWNER_NAME IS '대표자명';
COMMENT ON COLUMN TS02_TB_COMPANY.COMPANY_NO IS '사업자등록번호';

COMMENT ON COLUMN TS02_TB_COMPANY.TEL_PART1 IS '전화 앞번호';
COMMENT ON COLUMN TS02_TB_COMPANY.TEL_PART2 IS '전화 중간번호';
COMMENT ON COLUMN TS02_TB_COMPANY.TEL_PART3 IS '전화 뒷번호';
COMMENT ON COLUMN TS02_TB_COMPANY.POST_CODE IS '우편번호';
COMMENT ON COLUMN TS02_TB_COMPANY.ADDR_PART1 IS '주소1';

COMMENT ON COLUMN TS02_TB_COMPANY.ADDR_PART2 IS '주소2';
COMMENT ON COLUMN TS02_TB_COMPANY.DESCR IS '비고';
COMMENT ON COLUMN TS02_TB_COMPANY.INPUT_USER IS '등록자 OID';
COMMENT ON COLUMN TS02_TB_COMPANY.INPUT_DATE IS '등록일';
COMMENT ON COLUMN TS02_TB_COMPANY.ORDER_NO IS '정렬순서';





---------------------------------------------------------------
-- TS02_TB_GROUP : 그룹 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_GROUP (
  OID 				VARCHAR2(11) 	NOT NULL,
  NAME 				VARCHAR2(255) 	NULL,
  PARENT_OID 		VARCHAR2(11) 	NULL,
  FULL_PATH_INDEX 	VARCHAR2(700) 	DEFAULT '0|' NULL,
  SUB_LAST_INDEX 	NUMBER(5) 		DEFAULT -1 NULL,

  OWNER 			VARCHAR2(11) 	NULL,
  INPUT_USER 		VARCHAR2(11) 	NULL,
  INPUT_DATE 		DATE 			NULL,
  COMPANY_OID 		VARCHAR2(11) 	NULL,
  BRANCH_OID 		VARCHAR2(11) 	NULL,

  CUSTOM_FIELD1 	VARCHAR2(255) 	NULL,
  CUSTOM_FIELD2 	VARCHAR2(255) 	NULL,
  CUSTOM_FIELD3 	VARCHAR2(255) 	NULL,
  CUSTOM_FIELD4 	VARCHAR2(255) 	NULL,
  CUSTOM_FIELD5 	VARCHAR2(255) 	NULL,
  CONSTRAINT TS02_TB_GROUP PRIMARY KEY  ( OID )
);

COMMENT ON TABLE TS02_TB_GROUP IS '부서 테이블';

COMMENT ON COLUMN TS02_TB_GROUP.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_GROUP.NAME IS 'NAME';
COMMENT ON COLUMN TS02_TB_GROUP.PARENT_OID IS 'PARENT_OID';
COMMENT ON COLUMN TS02_TB_GROUP.FULL_PATH_INDEX IS 'Tree 구조를 가지는 Object의 경우 자신의 FullPathIndex';
COMMENT ON COLUMN TS02_TB_GROUP.SUB_LAST_INDEX IS 'Tree구조를 가지는 Object가 FullPathIndex를 구성하기 위하여 가지는 값';

COMMENT ON COLUMN TS02_TB_GROUP.OWNER IS '오너';
COMMENT ON COLUMN TS02_TB_GROUP.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_GROUP.INPUT_DATE IS '등록일';
COMMENT ON COLUMN TS02_TB_GROUP.COMPANY_OID IS '회사 아이디';
COMMENT ON COLUMN TS02_TB_GROUP.BRANCH_OID IS '해당팀의 지점 OID';

COMMENT ON COLUMN TS02_TB_GROUP.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_TB_GROUP.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_TB_GROUP.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_TB_GROUP.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_TB_GROUP.CUSTOM_FIELD5 IS '커스텀 필드5';



---------------------------------------------------------------
--  TS02_TB_USER : 사용자 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_USER (
  OID 				 VARCHAR2(11) 	NOT NULL,
  USER_ID			 VARCHAR2(255) 	NULL,
  NAME 				 VARCHAR2(255) 	NULL,
  ENG_NAME 			 VARCHAR2(255) 	NULL,
  PWD 				 VARCHAR2(255) 	NULL,
  PWD2 				 VARCHAR2(255) 	NULL,

  USER_TYPE 		 VARCHAR2(8) 	NULL,
  EMAIL 			 VARCHAR2(255) 	NULL,
  TEL_PART1 		 VARCHAR2(4) 	NULL,
  TEL_PART2 		 VARCHAR2(4) 	NULL,
  TEL_PART3 		 VARCHAR2(4) 	NULL,

  PHONE_PART1 		 VARCHAR2(4) 	NULL,
  PHONE_PART2 		 VARCHAR2(4) 	NULL,
  PHONE_PART3 		 VARCHAR2(4) 	NULL,
  NICK 				 VARCHAR2(255) 	NULL,
  BIRTH_YEAR         VARCHAR2(4) 	NULL,

  BIRTH_MONTH        VARCHAR2(4) 	NULL,
  BIRTH_DAY 		 VARCHAR2(4) 	NULL,
  POST_CODE 		 VARCHAR2(7) 	NULL,
  ADDR_PART1 		 VARCHAR2(500) 	NULL,
  ADDR_PART2 		 VARCHAR2(500) 	NULL,

  STATUS_TYPE_FLAG 	 CHAR(1) 		DEFAULT 'U' NULL,
  JOIN_TYPE 		 CHAR(1) 		DEFAULT 'W' NULL,
  JOIN_PATH_OPT_OID  VARCHAR2(11) 	NULL,
  JOIN_PATH_DESCR 	 VARCHAR2(255) 	NULL,
  JOIN_DATE 		 DATE 			NULL,

  COMPANY_OID 		 VARCHAR2(11) 	NULL,
  ORG_CODE 			 VARCHAR2(255) 	NULL,
  ORG_NAME 			 VARCHAR2(255) 	NULL,
  BRANCH_OID 		 VARCHAR2(11) 	NULL,
  GROUP_OID 		 VARCHAR2(11) 	NULL,

  RANK 				 VARCHAR2(20) 	NULL,
  POSITION 			 VARCHAR2(255) 	NULL,
  JOB 				 VARCHAR2(255) 	NULL,
  INPUT_USER 		 VARCHAR2(11) 	NULL,
  INPUT_DATE 		 DATE 			DEFAULT SYSDATE NULL,

  HIRE_DATE 		 DATE 			NULL,
  RETIRE_DATE 		 DATE 			NULL,
  UPDATE_DATE 		 DATE 			NULL,
  DESCR 			 VARCHAR2(500) 	NULL,
  EMP_NO 			 VARCHAR2(20) 	NULL,

  SEX 				 CHAR(1) 		NULL,
  REGION 			 VARCHAR2(8) 	NULL,
  ID_NO 			 VARCHAR2(255) 	NULL,

  BANK 				 VARCHAR2(20)  	NULL,
  ACCOUNT_NO 		 VARCHAR2(45) 	NULL,
  SALARY_TYPE 		 VARCHAR2(8) 	NULL,
  SALARY 			 NUMBER(10) 	NULL,

  WORK_FROM_TIME 	 VARCHAR2(10) 	NULL,
  WORK_TO_TIME 		 VARCHAR2(10) 	NULL,
  SNS_ID 			 VARCHAR2(255) 	NULL,
  SNS_JOIN_TYPE_FLAG CHAR(1)        NULL,

  CUSTOM_FIELD1 	 VARCHAR2(255) 	NULL,
  CUSTOM_FIELD2 	 VARCHAR2(255) 	NULL,
  CUSTOM_FIELD3 	 VARCHAR2(255) 	NULL,
  CUSTOM_FIELD4 	 VARCHAR2(255) 	NULL,
  CUSTOM_FIELD5 	 VARCHAR2(255) 	NULL,


  CONSTRAINT TS02_TB_USER PRIMARY KEY  ( OID )
);

COMMENT ON TABLE TS02_TB_USER IS '사용자 테이블';

COMMENT ON COLUMN TS02_TB_USER.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_USER.USER_ID  IS 'ID';
COMMENT ON COLUMN TS02_TB_USER.NAME  IS 'NAME';
COMMENT ON COLUMN TS02_TB_USER.ENG_NAME  IS '영문 이름';
COMMENT ON COLUMN TS02_TB_USER.PWD  IS 'PASSWORD';
COMMENT ON COLUMN TS02_TB_USER.PWD2   IS '이차 인증시 필요한 PASSWORD';

COMMENT ON COLUMN TS02_TB_USER.SNS_ID IS 'SNS ID';
COMMENT ON COLUMN TS02_TB_USER.SNS_JOIN_TYPE_FLAG IS 'SNS가입타입 - K: KAKAO, N:NAVER,F:FACEBOOK,G:GOOGLE';

COMMENT ON COLUMN TS02_TB_USER.USER_TYPE IS '유저타입(고객/회원/직원)';
COMMENT ON COLUMN TS02_TB_USER.EMAIL IS 'EMAIL';
COMMENT ON COLUMN TS02_TB_USER.TEL_PART1 IS '전화 앞번호';
COMMENT ON COLUMN TS02_TB_USER.TEL_PART2 IS '전화 중간번호';
COMMENT ON COLUMN TS02_TB_USER.TEL_PART3 IS '전화 뒷번호';

COMMENT ON COLUMN TS02_TB_USER.PHONE_PART1 IS '휴대전화 앞번호';
COMMENT ON COLUMN TS02_TB_USER.PHONE_PART2 IS '휴대전화 중간번호';
COMMENT ON COLUMN TS02_TB_USER.PHONE_PART3 IS '휴대전화 뒷번호';
COMMENT ON COLUMN TS02_TB_USER.NICK IS '닉네임';
COMMENT ON COLUMN TS02_TB_USER.BIRTH_YEAR IS '생년월일 년';

COMMENT ON COLUMN TS02_TB_USER.BIRTH_MONTH IS '생년월일 월';
COMMENT ON COLUMN TS02_TB_USER.BIRTH_DAY IS '생년월일 일';
COMMENT ON COLUMN TS02_TB_USER.POST_CODE IS '우편번호';
COMMENT ON COLUMN TS02_TB_USER.ADDR_PART1 IS '주소1';
COMMENT ON COLUMN TS02_TB_USER.ADDR_PART2 IS '주소2';

COMMENT ON COLUMN TS02_TB_USER.STATUS_TYPE_FLAG IS 'U 사용중, N 사용안함, A 승인대기, C 승인취소, W 탈퇴';
COMMENT ON COLUMN TS02_TB_USER.JOIN_TYPE IS '가입 경로 ( WEB (W), APP (A) )';
COMMENT ON COLUMN TS02_TB_USER.JOIN_PATH_OPT_OID IS '가입경로 옵션 OID';
COMMENT ON COLUMN TS02_TB_USER.JOIN_PATH_DESCR IS '가입경로 내용';
COMMENT ON COLUMN TS02_TB_USER.JOIN_DATE IS '회원가입 일시';

COMMENT ON COLUMN TS02_TB_USER.COMPANY_OID IS '회사 아이디 - 시스템 내부에서 company를 관리할때 사용';
COMMENT ON COLUMN TS02_TB_USER.ORG_CODE IS '조직(기관) 코드 - 외부에서 조직을 받아서 관리할때 사용';
COMMENT ON COLUMN TS02_TB_USER.ORG_NAME IS '조직(기관) 이름';

COMMENT ON COLUMN TS02_TB_USER.BRANCH_OID IS '지점 OID';
COMMENT ON COLUMN TS02_TB_USER.GROUP_OID IS '그룹 아이디';
COMMENT ON COLUMN TS02_TB_USER.RANK IS '직급';
COMMENT ON COLUMN TS02_TB_USER.POSITION IS '직책';

COMMENT ON COLUMN TS02_TB_USER.JOB IS '직무';
COMMENT ON COLUMN TS02_TB_USER.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_USER.INPUT_DATE IS '등록일';
COMMENT ON COLUMN TS02_TB_USER.HIRE_DATE IS '입사일';
COMMENT ON COLUMN TS02_TB_USER.RETIRE_DATE IS '퇴사일';
COMMENT ON COLUMN TS02_TB_USER.UPDATE_DATE IS '수정일';

COMMENT ON COLUMN TS02_TB_USER.DESCR IS '비고';
COMMENT ON COLUMN TS02_TB_USER.EMP_NO IS '사원번호';
COMMENT ON COLUMN TS02_TB_USER.SEX IS '성별';
COMMENT ON COLUMN TS02_TB_USER.REGION IS '지역코드';
COMMENT ON COLUMN TS02_TB_USER.ID_NO IS '주민등록번호';

COMMENT ON COLUMN TS02_TB_USER.BANK IS '은행';
COMMENT ON COLUMN TS02_TB_USER.ACCOUNT_NO IS '계좌번호';
COMMENT ON COLUMN TS02_TB_USER.SALARY_TYPE IS '급여타입';
COMMENT ON COLUMN TS02_TB_USER.SALARY IS '급여';

COMMENT ON COLUMN TS02_TB_USER.WORK_FROM_TIME IS '업무 시작시간';
COMMENT ON COLUMN TS02_TB_USER.WORK_TO_TIME IS '업무 종료시간';

COMMENT ON COLUMN TS02_TB_USER.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_TB_USER.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_TB_USER.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_TB_USER.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_TB_USER.CUSTOM_FIELD5 IS '커스텀 필드5';
