-- TS02_TB_BRANCH : 지점 테이블
DROP TABLE TS02_TB_BRANCH;

-- TS02_TB_COMPANY : 회사 테이블
DROP TABLE TS02_TB_COMPANT;

-- TS02_TB_GROUP : 그룹 테이블
DROP TABLE TS02_TB_GROUP;

--  TS02_TB_USER : 사용자 테이블
DROP TABLE TS02_TB_USER;
