---------------------------------------------------------------
-- 파일 다운로드 이력 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_AUDIT_FILE_DOWN (
  OID 					VARCHAR2(11) 			NOT NULL,
  FILE_OID		 		VARCHAR2(11) 			NOT NULL,
  POSTING_OID 			VARCHAR2(11) 			NULL,
  BOARD_OID 			VARCHAR2(11) 			NULL,

  DOWN_USER	 			VARCHAR2(11) 			NULL,
  DOWN_DATE				DATE 					NULL,
  CONSTRAINT TS02_TB_FILE_DOWN_AUDIT PRIMARY KEY(OID)
);

COMMENT ON TABLE TS02_TB_AUDIT_FILE_DOWN IS '파일 다운로드 이력 테이블';

COMMENT ON COLUMN TS02_TB_AUDIT_FILE_DOWN.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_AUDIT_FILE_DOWN.FILE_OID IS '파일 OID';
COMMENT ON COLUMN TS02_TB_AUDIT_FILE_DOWN.POSTING_OID IS '포스팅 OID';
COMMENT ON COLUMN TS02_TB_AUDIT_FILE_DOWN.BOARD_OID IS '보드 OID';

COMMENT ON COLUMN TS02_TB_AUDIT_FILE_DOWN.DOWN_USER IS '다운로드한 사용자';
COMMENT ON COLUMN TS02_TB_AUDIT_FILE_DOWN.DOWN_DATE IS '다운로드한 일시';



---------------------------------------------------------------
--  TS02_TB_AUDIT_VIEW : 조회 이력 테이블 - 게시물은 별도처리
---------------------------------------------------------------
CREATE TABLE TS02_TB_AUDIT_VIEW (
  OID 					VARCHAR2(11) 			NOT NULL,
  TARGET_OBJECT 		VARCHAR2(4) 			NULL,
  TARGET_OID 			VARCHAR2(11) 			NULL,
  VIEW_USER 			VARCHAR2(11) 			NULL,
  VIEW_DATE 			DATE 					NULL,
  
  VIEW_YEAR             VARCHAR2(4)            NULL,
  VIEW_MONTH             VARCHAR2(2)            NULL,
  VIEW_WEEK             VARCHAR2(1)            NULL,
  VIEW_DAY             VARCHAR2(2)            NULL,
  CONSTRAINT TS02_TB_AUDIT_VIEW PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_AUDIT_VIEW IS '조회이력 테이블';

COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.TARGET_OBJECT IS '타겟 객체';
COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.TARGET_OID IS '타겟 OID';
COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.VIEW_USER IS '조회자 OID';
COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.VIEW_DATE IS '조회 일시';

COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.VIEW_YEAR IS '조회 년';
COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.VIEW_MONTH IS '조회 월';
COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.VIEW_WEEEK IS '조회 주';
COMMENT ON COLUMN TS02_TB_AUDIT_VIEW.VIEW_DAY IS '조회 일';

---------------------------------------------------------------
--  TS02_TB_AUDIT_VISIT ㅣ 방문 이력 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_AUDIT_VISIT (
  OID 					VARCHAR2(11) 			NOT NULL,
  VISIT_YEAR    		VARCHAR2(4) 			NOT NULL,
  VISIT_MONTH			VARCHAR2(2) 			NOT NULL,
  VISIT_WEEK			VARCHAR2(1) 			NOT NULL,
  VISIT_DAY				VARCHAR2(2)	 			NOT NULL,
  
  USER_IP 				VARCHAR2(20) 			NULL,
  USER_AGENT 			VARCHAR2(30) 			NULL,
  INPUT_DATE 			DATE DEFAULT SYSDATE 	NULL,
  CONSTRAINT TS02_TB_AUDIT_VISIT PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_AUDIT_VISIT IS '방문 이력 테이블';

COMMENT ON COLUMN TS02_TB_AUDIT_VISIT.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_AUDIT_VISIT.VISIT_YEAR IS '등록 년';
COMMENT ON COLUMN TS02_TB_AUDIT_VISIT.VISIT_MONTH IS '등록 월';
COMMENT ON COLUMN TS02_TB_AUDIT_VISIT.VISIT_WEEK IS '등록 주';
COMMENT ON COLUMN TS02_TB_AUDIT_VISIT.VISIT_DAY IS '등록 일';

COMMENT ON COLUMN TS02_TB_AUDIT_VISIT.USER_IP IS '사용자 IP';
COMMENT ON COLUMN TS02_TB_AUDIT_VISIT.USER_AGENT IS '연결타입 웹인지 모바일인지 구분하기 위해. navigator.userAgent을 체크하여 ipad, iphone, android, shw 등의 값';
COMMENT ON COLUMN TS02_TB_AUDIT_VISIT.INPUT_DATE IS '방문 일시';

