---------------------------------------------------------------
-- 사용자 기기 뷰
-- 사용 테이블 : TS02_TB_DEVICE, TS02_TB_USER
---------------------------------------------------------------
CREATE OR REPLACE VIEW VS02_USER_DEVICE AS
SELECT
    D.OID AS OID,
    D.DEVICE_MODEL_NAME AS DEVICE_MODEL_NAME,
    D.SERIAL_NUM AS SERIAL_NUM,
    D.PUSH_TOKEN AS PUSH_TOKEN,
    D.PUSH_YN AS PUSH_YN,

    D.IMEI AS IMEI,
    D.BUILD_VERSION AS BUILD_VERSION,
    D.OS_TYPE_FLAG AS OS_TYPE_FLAG,
    D.APP_VERSION AS APP_VERSION,
    D.OS_VERSION AS OS_VERSION,

    D.UUID AS UUID,
    D.INPUT_DATE AS INPUT_DATE,

    USR.OID AS USER_OID,
    USR.ID AS USER_ID,
    USR.NAME AS USER_NAME,
    USR.PWD AS USER_PWD,
    USR.EMAIL AS USER_EMAIL,

    USR.TEL_PART1 AS USER_TEL_PART1,
    USR.TEL_PART2 AS USER_TEL_PART2,
    USR.TEL_PART3 AS USER_TEL_PART3,
    USR.PHONE_PART1 AS USER_PHONE_PART1,
    USR.PHONE_PART2 AS USER_PHONE_PART2,
    USR.PHONE_PART3 AS USER_PHONE_PART3,

    USR.NICK AS USER_NICK,
    USR.YEAR AS USER_YEAR,
    USR.MONTH AS USER_MONTH,
    USR.DAY AS USER_DAY,

    USR.POST_CODE AS USER_POST_CODE,
    USR.ADDR_PART1 AS USER_ADD_PART1,
    USR.ADDR_PART2 AS USER_ADDR_PART2,
    USR.STATUS_TYPE_FLAG AS USER_STATUS_TYPE_FLAG,
    USR.JOIN_TYPE AS USER_JOIN_TYPE,

    USR.GROUP_OID AS USER_GROUP_OID,
    USR.RANK AS USER_RANK,
    USR.INPUT_USER AS USER_INPUT_USER,
    USR.INPUT_DATE AS USER_INPUT_DATE,
    USR.HIRE_DATE AS USER_HIRE_DATE,

    USR.RETIRE_DATE AS USER_RETIRE_DATE,
    USR.DESCR AS USER_DESCR,
    USR.EMP_NO AS USER_EMP_NO,
    DREL.USE_YN AS REL_USE_YN
FROM TS02_TB_DEVICE D
JOIN TS02_TB_USER_DEVICE_REL DREL
ON D.UUID = DREL.UUID
JOIN TS02_TB_USER USR
ON DREL.USER_OID = USR.OID
