---------------------------------------------------------------
--  TS02_TB_DEVICE : 기기정보 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_DEVICE (
	OID 				VARCHAR2(11) 		NOT NULL,
	DEVICE_MODEL_NAME 	VARCHAR2(100) 		NULL,
	SERIAL_NUM 			VARCHAR2(100) 		NULL,
	IMEI 				VARCHAR2(100) 		NULL,
	BUILD_VERSION 		VARCHAR2(100) 		NULL,

	OS_TYPE_FLAG 		CHAR(1) 			NULL,
	APP_VERSION 		VARCHAR2(100) 		NULL,
	OS_VERSION 			VARCHAR2(100) 		NULL,
	UUID 				VARCHAR2(36) 		NOT NULL,
	PUSH_TOKEN 			VARCHAR2(300) 		NULL,

	PUSH_YN 			CHAR(1) 			NULL,
	INPUT_DATE 			DATE DEFAULT SYSDATE NOT NULL,
	CONSTRAINT TS02_TB_DEVICE PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_DEVICE IS '기기정보 테이블';

COMMENT ON COLUMN TS02_TB_DEVICE.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_DEVICE.DEVICE_MODEL_NAME IS '기기명';
COMMENT ON COLUMN TS02_TB_DEVICE.SERIAL_NUM IS '시리얼 넘버';
COMMENT ON COLUMN TS02_TB_DEVICE.IMEI IS 'IMEI';
COMMENT ON COLUMN TS02_TB_DEVICE.BUILD_VERSION IS 'BUILD_VERSION';

COMMENT ON COLUMN TS02_TB_DEVICE.OS_TYPE_FLAG IS '안드로이드, 아이폰';
COMMENT ON COLUMN TS02_TB_DEVICE.APP_VERSION IS '앱 버전';
COMMENT ON COLUMN TS02_TB_DEVICE.OS_VERSION IS 'OS 버전';
COMMENT ON COLUMN TS02_TB_DEVICE.UUID IS '안드로이드/아이폰 기기고유 ID';
COMMENT ON COLUMN TS02_TB_DEVICE.PUSH_TOKEN IS 'Push용 PUSH TOKEN';

COMMENT ON COLUMN TS02_TB_DEVICE.PUSH_YN IS 'PUSH 수신설정 여부';
COMMENT ON COLUMN TS02_TB_DEVICE.INPUT_DATE IS '등록 일시';






---------------------------------------------------------------
--  TS02_TB_USER_DEVICE_REL : 유저 기기정보 REL 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_USER_DEVICE_REL (
   USER_OID 			VARCHAR2(11) 			NOT NULL,
   UUID 				VARCHAR2(36) 			NOT NULL,
   INPUT_DATE 			DATE DEFAULT SYSDATE 	NOT NULL,
   USE_YN 				CHAR(1) DEFAULT 'Y' 	NOT NULL,
   CONSTRAINT TS02_TB_USER_DEVICE_REL PRIMARY KEY ( USER_OID, UUID )
);

COMMENT ON TABLE TS02_TB_USER_DEVICE_REL IS '유저 기기정보 릴레이션 테이블';

COMMENT ON COLUMN TS02_TB_USER_DEVICE_REL.USER_OID IS '유저 OID';
COMMENT ON COLUMN TS02_TB_USER_DEVICE_REL.UUID IS '기기고유 ID';
COMMENT ON COLUMN TS02_TB_USER_DEVICE_REL.INPUT_DATE IS '등록 일시';
COMMENT ON COLUMN TS02_TB_USER_DEVICE_REL.USE_YN IS '기기사용 여부';


