-- TS02_TB_POSTING_AUDIT_VIEW  : 게시물 보기이력 테이블
DROP TABLE TS02_TB_POSTING_AUDIT_VIEW;

-- TS02_TB_BOARD : 보드 테이블
DROP TABLE TS02_TB_BOARD;

-- TS02_TB_CONTENTS  : 컨텐츠 테이블
DROP TABLE TS02_TB_CONTENTS;

-- TS02_TB_POSTING  : 게시물 테이블
DROP TABLE TS02_TB_POSTING;
