---------------------------------------------------------------
-- TS02_TB_API_KEY : API_KEY 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_API_KEY (
  OID 					VARCHAR2(11) 		NOT NULL,
  TARGET_OBJECT 		VARCHAR2(4) 		NULL,
  TARGET_OID 			VARCHAR2(11) 		NULL,
  API_KEY 				VARCHAR2(255) 		NULL,
  API_KEY_TYPE 			VARCHAR2(8) 		NULL,

  SEND_ID 				VARCHAR2(255) 		NULL,
  SEND_PHONE 			VARCHAR2(20) 		NULL,
  USE_YN 				CHAR(1) 			NOT NULL,
  INPUT_DATE 			DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT TS02_TB_API_KEY PRIMARY KEY ( OID )
);

COMMENT ON TABLE TS02_TB_API_KEY IS 'API_KEY 발급이력 테이블';

COMMENT ON COLUMN TS02_TB_API_KEY.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_API_KEY.TARGET_OBJECT IS '타겟 객체타입';
COMMENT ON COLUMN TS02_TB_API_KEY.TARGET_OID IS '타겟 OID';
COMMENT ON COLUMN TS02_TB_API_KEY.API_KEY IS 'API KEY';
COMMENT ON COLUMN TS02_TB_API_KEY.API_KEY_TYPE IS 'API KEY 타입(문자, 카카오, 자체발급 등)';

COMMENT ON COLUMN TS02_TB_API_KEY.SEND_ID IS '발신자ID';
COMMENT ON COLUMN TS02_TB_API_KEY.SEND_PHONE IS '발신자번호';
COMMENT ON COLUMN TS02_TB_API_KEY.USE_YN IS 'API KEY 사용 여부';
COMMENT ON COLUMN TS02_TB_API_KEY.INPUT_DATE IS '생성 일시';




---------------------------------------------------------------
-- TS02_TB_BATCH_PROCESS : 배치 진행상황 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_BATCH_PROCESS (
  OID 					VARCHAR2(11) 		NOT NULL,
  BATCH_NAME 			VARCHAR2(255) 		NOT NULL,
  THREAD_NAME 			VARCHAR2(255) 		NULL,
  CLASS_NAME 			VARCHAR2(255) 		NULL,
  API_NAME 				VARCHAR2(255) 		NULL,

  EXECUTE_YN 			CHAR(1) 			NULL,
  SUCCESS_YN 			CHAR(1) 			NULL,
  TOTAL_CNT 			NUMBER(10) 			NULL,
  SUCCESS_CNT 			NUMBER(10) 			NULL,
  FAIL_CNT 				NUMBER(10) 			NULL,

  START_TIME 			VARCHAR2(50) 		NULL,
  ELAPSED_TIME 			NUMBER(20) 			NULL,
  DESCR 				VARCHAR2(500) 		NULL,
  INPUT_DATE 			DATE 				NOT NULL,
  CONSTRAINT TS02_TB_BATCH_PROCESS PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_BATCH_PROCESS IS '배치 진행상황 테이블';

COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.BATCH_NAME IS '배치명';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.THREAD_NAME IS '스레드명';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.CLASS_NAME IS '배치 클래스명';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.API_NAME IS '배치 API명';

COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.EXECUTE_YN IS '배치 실행 성공 여부';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.SUCCESS_YN IS '배치 성공 여부';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.TOTAL_CNT IS '총 카운트';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.SUCCESS_CNT IS '성공 카운트';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.FAIL_CNT IS '실패 카운트';

COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.START_TIME IS '시작시간';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.ELAPSED_TIME IS '걸린시간 Millis';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.DESCR IS '설명';
COMMENT ON COLUMN TS02_TB_BATCH_PROCESS.INPUT_DATE IS '등록일시';





---------------------------------------------------------------
-- TS02_TB_CATEGORY : 카테고리 테이블 - 계층형구조를 나타낼때 사용
---------------------------------------------------------------
CREATE TABLE TS02_TB_CATEGORY (
  OID 						VARCHAR2(11) 			NOT NULL,
  PART_OID 					VARCHAR2(11) 			NULL,
  CATEGORY_TYPE				VARCHAR2(8) 			NULL,

  PARENT_OID 				VARCHAR2(11) 			NULL,
  FULL_PATH_INDEX 			VARCHAR2(700) 			DEFAULT '0|' NULL,
  SUB_LAST_INDEX 			NUMBER(10) 				DEFAULT -1 NULL,
  ORDER_NO 					NUMBER(5)				NULL,
  DISPLAY_YN				CHAR(1)					NULL,

  CUSTOM_FIELD1 			VARCHAR2(255) 			NULL,
  CUSTOM_FIELD2 			VARCHAR2(255) 			NULL,
  CUSTOM_FIELD3 			VARCHAR2(255) 			NULL,
  CUSTOM_FIELD4 			VARCHAR2(255) 			NULL,
  CUSTOM_FIELD5 			VARCHAR2(255) 			NULL,

  CONSTRAINT TS02_TB_CATEGORY PRIMARY KEY( OID )
);

COMMENT ON TABLE TS02_TB_CATEGORY IS '카테고리 테이블';

COMMENT ON COLUMN TS02_TB_CATEGORY.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_CATEGORY.PART_OID IS 'PART OID';
COMMENT ON COLUMN TS02_TB_CATEGORY.CATEGORY_TYPE IS '카테고리 타입  - FWCA00GL - 일반, FWCA00BD - 보드, FWCA00SU - 설문, FWCA00SC - 스케줄, FWCALSCL - 강좌, FWCALSLE - 강의';
COMMENT ON COLUMN TS02_TB_CATEGORY.NAME IS '이름';
COMMENT ON COLUMN TS02_TB_CATEGORY.PARENT_OID IS 'PARENT_OID';

COMMENT ON COLUMN TS02_TB_CATEGORY.FULL_PATH_INDEX IS 'Tree구조를 가지는 Object의 경우 자신의 FullPathIndex';
COMMENT ON COLUMN TS02_TB_CATEGORY.SUB_LAST_INDEX IS 'Tree구조를 가지는 Object가 FullPathIndex를 구성하기 위하여 가지는 값';
COMMENT ON COLUMN TS02_TB_CATEGORY.ORDER_NO IS '정렬순서';
COMMENT ON COLUMN TS02_TB_CATEGORY.DESCR IS '설명';

COMMENT ON COLUMN TS02_TB_CATEGORY.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_CATEGORY.INPUT_DATE IS '등록일시';
COMMENT ON COLUMN TS02_TB_CATEGORY.MOD_DATE IS '수정일';
COMMENT ON COLUMN TS02_TB_CATEGORY.MOD_USER IS '수정자';
COMMENT ON COLUMN TS02_TB_CATEGORY.DISPLAY_YN IS '게시여부';

COMMENT ON COLUMN TS02_TB_CATEGORY.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_TB_CATEGORY.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_TB_CATEGORY.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_TB_CATEGORY.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_TB_CATEGORY.CUSTOM_FIELD5 IS '커스텀 필드5';




---------------------------------------------------------------
-- TS02_TB_CATEGORY_LANG : 카테고리 다국어 테이블 - 카테고리의 다국어 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_CATEGORY_LANG (
  OID 						VARCHAR2(11) 			NOT NULL,
  LANG						VARCHAR2(2) 			NOT NULL,
  NAME 						VARCHAR2(255) 			NULL,
  DESCR 					VARCHAR2(4000) 			NULL,

  INPUT_USER 				VARCHAR2(11) 			NULL,
  INPUT_DATE 				DATE 					NULL,
  MOD_USER                  VARCHAR2(11)            NULL,
  MOD_DATE                  DATE                    NULL,

  CONSTRAINT TS02_TB_CATEGORY_LANG PRIMARY KEY( OID, LANG )
);

COMMENT ON TABLE TS02_TB_CATEGORY_LANG IS '카테고리 테이블';

COMMENT ON COLUMN TS02_TB_CATEGORY_LANG.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_CATEGORY_LANG.LANG IS 'LANG';
COMMENT ON COLUMN TS02_TB_CATEGORY.NAME IS '이름';
COMMENT ON COLUMN TS02_TB_CATEGORY.DESCR IS '설명';

COMMENT ON COLUMN TS02_TB_CATEGORY.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_CATEGORY.INPUT_DATE IS '등록일시';
COMMENT ON COLUMN TS02_TB_CATEGORY.MOD_DATE IS '수정일';
COMMENT ON COLUMN TS02_TB_CATEGORY.MOD_USER IS '수정자';


---------------------------------------------------------------
--  TS02_TB_CODE : 공통 코드 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_CODE (
	OID 				VARCHAR2(11) 		NOT NULL,
	CODE 				VARCHAR2(8) 		NULL,
	CODE_NAME 			VARCHAR2(100) 		NULL,
	CODE_VALUE 			VARCHAR2(100) 		NULL,
	CODE_LEVEL 			NUMBER(10) 			NULL,

	PARENT_CODE 		VARCHAR2(8) 		NULL,
	CODE_TYPE           VARCHAR2(8)         NULL,
	USE_YN 				CHAR(1) 			NULL,
	DELETE_YN 			CHAR(1) 			NULL,
	ORDER_NO 			NUMBER(5)			NULL,

	CUSTOM_FIELD1 		VARCHAR2(255) 		NULL,
	CUSTOM_FIELD2 		VARCHAR2(255) 		NULL,
	CUSTOM_FIELD3 		VARCHAR2(255) 		NULL,
	CUSTOM_FIELD4 		VARCHAR2(255) 		NULL,
	CUSTOM_FIELD5 		VARCHAR2(255) 		NULL,
	CONSTRAINT TS02_TB_CODE PRIMARY KEY ( OID )
);

COMMENT ON TABLE TS02_TB_CODE IS '코드 테이블';

COMMENT ON COLUMN TS02_TB_CODE.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_CODE.CODE IS '코드';
COMMENT ON COLUMN TS02_TB_CODE.CODE_NAME IS '코드 명';
COMMENT ON COLUMN TS02_TB_CODE.CODE_VALUE IS '코드 값';
COMMENT ON COLUMN TS02_TB_CODE.CODE_LEVEL IS '코드 레벨';

COMMENT ON COLUMN TS02_TB_CODE.PARENT_CODE IS '상위코드';
COMMENT ON COLUMN TS02_TB_CODE.CODE_TYPE IS '코드 타입';
COMMENT ON COLUMN TS02_TB_CODE.USE_YN IS '사용여부';
COMMENT ON COLUMN TS02_TB_CODE.DELETE_YN IS '삭제여부';
COMMENT ON COLUMN TS02_TB_CODE.ORDER_NO IS '정렬순서';

COMMENT ON COLUMN TS02_TB_CODE.CUSTOM_FIELD1 IS '커스텀 필드1';
COMMENT ON COLUMN TS02_TB_CODE.CUSTOM_FIELD2 IS '커스텀 필드2';
COMMENT ON COLUMN TS02_TB_CODE.CUSTOM_FIELD3 IS '커스텀 필드3';
COMMENT ON COLUMN TS02_TB_CODE.CUSTOM_FIELD4 IS '커스텀 필드4';
COMMENT ON COLUMN TS02_TB_CODE.CUSTOM_FIELD5 IS '커스텀 필드5';


---------------------------------------------------------------
-- TS02_TB_PART : 파트 테이블 - 시스템내의 내부 서비스단위. 카테고리의 부모. System > PART > Category > Board, Survery, Schedule
-- 소재구분 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_PART (
  OID 					VARCHAR2(11) 		NOT NULL,
  SYSTEM_OID            VARCHAR2(11)        NULL,
  NAME 					VARCHAR2(255) 		NULL,
  CLASS_NAME			VARCHAR2(255) 		NULL,

  INPUT_USER 			VARCHAR2(11) 		NULL,
  INPUT_DATE 			DATE 				NULL,
  CONSTRAINT TS02_TB_PART PRIMARY KEY( OID )
);


COMMENT ON TABLE TS02_TB_PART IS '파트 테이블';

COMMENT ON COLUMN TS02_TB_PART.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_PART.SYSTEM_OID IS '시스템 OID';
COMMENT ON COLUMN TS02_TB_PART.NAME IS '파트명';
COMMENT ON COLUMN TS02_TB_PART.CLASS_NAME IS 'part 분류명 - 자신이 분류한 분류명으로 구분 ex) 원격연수, 교직원집합연수';

COMMENT ON COLUMN TS02_TB_PART.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_PART.INPUT_DATE IS '등록일시';


---------------------------------------------------------------
--  TS02_TB_SYSTEM : 시스템 테이블 외부에서 각 회사마다 사용하는 시스템과 내부에서 여러 시스템을 구분하는 용도로 사용
---------------------------------------------------------------
CREATE TABLE TS02_TB_SYSTEM (
   OID 		    		VARCHAR2(11) 			NOT NULL,
   COMPANY_OID 	    	VARCHAR2(11) 			NULL,
   NAME 				VARCHAR2(255) 			NOT NULL,
   DESCR 				VARCHAR2(500) 			NULL,
   ORDER_NO 			NUMBER(5) 				NULL,

   USE_YN 				CHAR(1) 				NULL,
   MANAGER_OID 		    VARCHAR2(11) 			NULL,
   INPUT_USER 			VARCHAR2(11) 			NOT NULL,
   INPUT_DATE 			DATE    DEFAULT SYSDATE NOT NULL,
   CONSTRAINT TS02_TB_SYSTEM PRIMARY KEY (OID)
);


COMMENT ON TABLE TS02_TB_SYSTEM IS '시스템 테이블 외부에서 각 회사마다 사용하는 시스템과 내부에서 여러 시스템을 구분하는 용도로 사용';

COMMENT ON COLUMN TS02_TB_SYSTEM.OID IS 'OID';
COMMENT ON COLUMN TS02_TB_SYSTEM.COMPANY_OID IS '회사OID';
COMMENT ON COLUMN TS02_TB_SYSTEM.NAME IS '시스템명';
COMMENT ON COLUMN TS02_TB_SYSTEM.DESCR IS '설명';
COMMENT ON COLUMN TS02_TB_SYSTEM.ORDER_NO IS '정렬순서';

COMMENT ON COLUMN TS02_TB_SYSTEM.USE_YN IS '사용여부';
COMMENT ON COLUMN TS02_TB_SYSTEM.MANAGER_OID IS '관리자 OID';
COMMENT ON COLUMN TS02_TB_SYSTEM.INPUT_USER IS '등록자';
COMMENT ON COLUMN TS02_TB_SYSTEM.INPUT_DATE IS '등록일';


---------------------------------------------------------------
--  TS02_TB_SYSTEM_DETAIL : 시스템 상세 테이블
---------------------------------------------------------------
CREATE TABLE TS02_TB_SYSTEM_DETAIL (
  SYSTEM_OID 			VARCHAR2(11) 			NULL,
  SERVICE_URL 		VARCHAR2(255) 			NULL,
  SUCCESS_URL 		VARCHAR2(255) 			NULL,
  SEND_TYPE_MODE 		NUMBER(5) 				NULL,

  VALID_SECOND_TIME 	VARCHAR2(4) 			NULL,
  VALID_CNT 			VARCHAR2(2) 			NULL,
  CONSTRAINT TS02_TB_SYSTEM_DETAIL PRIMARY KEY (SYSTEM_OID)
);

COMMENT ON TABLE TS02_TB_SYSTEM_DETAIL IS '시스템 상세 테이블';

COMMENT ON COLUMN TS02_TB_SYSTEM_DETAIL.SYSTEM_OID IS 'SYSTEM OID';
COMMENT ON COLUMN TS02_TB_SYSTEM_DETAIL.SERVICE_URL IS '서비스주소';
COMMENT ON COLUMN TS02_TB_SYSTEM_DETAIL.SUCCESS_URL IS '접속 성공 URL';
COMMENT ON COLUMN TS02_TB_SYSTEM_DETAIL.SEND_TYPE_MODE IS '전송 방식 (친구톡/알림톡/SMS/Push/....)';

COMMENT ON COLUMN TS02_TB_SYSTEM_DETAIL.VALID_SECOND_TIME IS '유효 초 시간';
COMMENT ON COLUMN TS02_TB_SYSTEM_DETAIL.VALID_CNT IS '로그인 시도 가능 횟수';