
-- TS02_TB_API_KEY : API_KEY 테이블
DROP TABLE API_KEY;

-- TS02_TB_BATCH_PROCESS : 배치 진행상황 테이블
DROP TABLE TS02_TB_BATCH_PROCESS;

-- TS02_TB_CATEGORY : 카테고리 테이블 - 계층형구조를 나타낼때 사용
DROP TABLE TS02_TB_CATEGORY;

--  TS02_TB_CODE : 공통 코드 테이블
DROP TABLE TS02_TB_CODE;

-- TS02_TB_PART : PART 테이블
DROP TABLE TS02_TB_PART;

--  TS02_TB_SYSTEM : 시스템 테이블 외부에서 각 회사마다 사용하는 시스템과 내부에서 여러 시스템을 구분하는 용도로 사용
DROP TABLE TS02_TB_SYSTEM;

--  TS02_TB_SYSTEM_DETAIL : 시스템 상세 테이블
DROP TABLE TS02_TB_SYSTEM_DETAIL;